### ISSUE TITLE
Issue on saving the route map as .json file

### ISSUE THREAD

**Issue by ThomasCheung02** [railmapgen/rmg#130]
我已經下載了思源宋體，可是在儲存我的路線圖為.json檔案時卻仍然顯示這個畫面：
<img width="771" alt="Screenshot 2021-09-06 at 12 34 05 PM" src="https://user-images.githubusercontent.com/90170314/132161083-cffa18b4-f39a-4c0b-9633-d5ee45373b50.png">
當中有些本來是中文文字卻變成亂碼。請問該怎麼解決？

**Comment by wongchito** [comment]
Hi Thomas,

麻煩閣下嘗試以下步驟，以便我們找到問題發生的原因：

1. 請提供閣下所使用之作業系統及其語言、以及瀏覽器及其語言
2. 請嘗試開啓程式預設之範本，不作任何變更並將其儲存為JSON，檢查所下載的JSON檔案是否包含亂碼

多謝

**Comment by ThomasCheung02** [comment]
1. 本人之
作業系統：MacOS Catalina 10.15.7
作業系統語言：English
瀏覽器：Safari
瀏覽器語言： English

2. 開啓程式預設之範本後，儲存為JSON時仍然顯示亂碼
<img width="824" alt="Screenshot 2022-02-14 at 12 47 22 PM" src="https://user-images.githubusercontent.com/90170314/153801709-c04711ba-a7ed-4d94-8d0c-d67195de9d5c.png">

**Comment by ThomasCheung02** [comment]
我已經下載了源樣明體及Vegur，並先後重新啟動瀏覽器和電腦；然後開啓程式預設之範本，不作任何變更並將其儲存為JSON。可是，所下載的JSON檔案仍然包含亂碼。

作業系統：MacOS Catalina 10.15.7
作業系統語言：English
瀏覽器：Safari
瀏覽器語言： English

<img width="824" alt="Screenshot 2022-02-14 at 12 47 22 PM" src="https://user-images.githubusercontent.com/90170314/153805542-ab31dc69-45e8-4837-9c77-2b52c5fde771.png">

我該如何解決？謝謝。

**Comment by wongchito** [comment]
你好，基於閣下所提供之資料，

1. 亂碼問題與字型下載無關。
2. 本人懷疑亂碼問題與程式字元編碼相關，但需作進一步調查。

我們將儘快回覆閣下或/及修正相關錯誤，多謝！

**Comment by XHG78999** [comment]
你好，

该issue已经经过了我们的内部讨论，确认有操作系统的可能，我们对此类现象还无法给出完整的解决方法。但是经过判断，您这边是我们的bug，我们会尽力解决的。

谢谢您对我们提出建议和报告漏洞。

**Comment by wongchito** [comment]
你好 @ThomasCheung02 ，

經多次於macOS英文作業系統上嘗試後，我們得出以下結論：
1. 若所儲存之JSON檔案被直接下載至「下載」資料夾，再以「TextEdit」程式開啓，檔案內容並不會出現亂碼。
2. 若所儲存之JSON檔案在「Safari」之新分頁中開啓，檔案內容會出現亂碼。這皆因「Safari」於英文作業系統下，預設字元編碼為「西歐 (Western ISO Lation 1)」，從而導致無法識別檔案中之漢字。

解決方案（2選1）：
1. 於閣下提供之螢幕截圖之界面下，右鍵並選取「儲存頁面為 (Save page as)」，然後以「.json」結尾儲存檔案。該檔案將包含非亂碼之字元，並可於RMG內正常讀取。
2. 在RMG點選「儲存」時，將檔案直接下載至「下載」資料夾，而非於新分頁中開啓。

另外，我們於測試中發現，我們無法令「Safari」於新分頁中開啓，想請問閣下如何於偏好設定變更此功能，以便我們日後測試及避免類似問題再次發生。多謝！

**Comment by XHG78999** [comment]
所以打个wontfix？

**Comment by thekingofcity** [comment]
> 所以打个wontfix？

至少等提问者再次回复后再说

**Comment by wongchito** [comment]
Closed as no reply.
