### ISSUE TITLE
Missing font for some CJK characters (Chinese simplified)

### ISSUE THREAD

**Issue by delick** [railmapgen/rmg#143]
Font for some CJK characters is not consistent with that of others. For example:
![image](https://user-images.githubusercontent.com/20290394/136247507-d25b303b-4e1a-41bf-9585-173c09117f4c.png)
in this image, '览' is in Serif (in Chrome online preview) or SimHei(in exported SVG) instead of Noto Serif.

I can see in output SVG file that there are some unicode range specified, which might be the cause:
```
unicode-range: U+26, U+5F, U+2026, U+203B, U+4E09, U+4EAC, U+4ED5, U+4FA1, U+5143, U+5199, U+5207, U+539F, U+53E3, U+53F7, U+5411, U+5473, U+5546, U+55B6, U+5929, U+597D, U+5BB9, U+5C11, U+5C4B, U+5DDD, U+5F97, U+5FC5, U+6295, U+6301, U+6307, U+671B, U+76F8, U+78BA, U+795E, U+7D30, U+7D39, U+7D9A, U+89E3, U+8A00, U+8A73, U+8A8D, U+8A9E, U+8AAD, U+8ABF, U+8CEA, U+8ECA, U+8FFD, U+904B, U+9650, U+FF11-FF12; } @font-face { font-family: "Noto Serif SC"; font-style: normal;
```

**Comment by delick** [comment]
Hi, thank you for detailed comparison between firefox and Chrome. I think this inconsistency in CJK font is fixed in online version (tested today on Mac).

Inconsistency in Electron app still exist:
![image](https://user-images.githubusercontent.com/20290394/136364685-e3e89bbc-711f-4f7c-a8d0-9261895c4935.png)
> Chrome on Mac (SVG exported) [港铁风格_exported.svg.zip](https://github.com/wongchito/RailMapGenerator/files/7301670/_exported.svg.zip)

It is using `rmg-name__zh rmg-name__mtr--station` class, which is probably the correct class for chinese station names. But still missing font for some simplified chinese characters.

In online version (tested today), there's no more font inconsistency:
![image](https://user-images.githubusercontent.com/20290394/136366662-ca04a8c7-4831-4e8e-a51c-53ba9574db1b.png)
> Chrome on Mac (Online preview)

At least no more sans-serif mixed with serif font in same station name.

But some characters, '埒' and '湾' for example, are not the standard simplified chinese version.
> 
![image](https://user-images.githubusercontent.com/20290394/136366869-0936cbff-ca1e-44dd-9a2b-170c2aa0e6d8.png)
> Example of '埒' and '湾' with Google Noto Sans CJK SC

This minor differences is acceptable, as it is Hong Kong MTR style.

Is it some unicode range specification that caused this bug?

**Comment by thekingofcity** [comment]
> But some characters, '埒' and '湾' for example, are not the standard simplified chinese version.
> 
> > 
> 
> ![image](https://user-images.githubusercontent.com/20290394/136366869-0936cbff-ca1e-44dd-9a2b-170c2aa0e6d8.png)
> 
> > Example of '埒' and '湾' with Google Noto Sans CJK SC
> 
> This minor differences is acceptable, as it is Hong Kong MTR style.
> 
> Is it some unicode range specification that caused this bug?

@wongchito Would you like to take a look at MTR specific font issue?

**Comment by delick** [comment]
> Hi, we release the latest electron packages versioned in 3.9.33 and see no issue:
> Would you like to update to [the latest version](https://github.com/wongchito/RailMapGenerator/releases/tag/rmg-3.9.33) and give another shot?

Hi, thank you for the updated version. 
Still missing font on Mac OS Chrome (tested on Oct 9, 2021). 

![image](https://user-images.githubusercontent.com/20290394/136644256-35b80180-e007-4e50-ac26-421964ee448d.png)
> Chrome Mac OS, SVG exported from RMG 3.9.33

Simplified characters, '润', '览', '线' for example, still not consistent with others. Same for online preview.

Online version 2 days ago (Oct 7, night) seems better:
![image](https://user-images.githubusercontent.com/20290394/136644361-4a7cbd2f-9b18-43b5-b570-f255b0d37fed.png)
> Chrome on Mac (Online preview), tested on Oct 7 evening.

**Comment by thekingofcity** [comment]
> Still missing font on Mac OS Chrome (tested on Oct 9, 2021).

Hi, could you confirm the font rendered in electron on mac is still not `Noto Serif TC`?

![image](https://user-images.githubusercontent.com/3353040/136665137-f58e8499-6cdd-4763-a564-8536aa85c7a2.png)

**Comment by thekingofcity** [comment]
> Hi, I think the character '览' in '博览中心' and '润' in '丰润道' are not even serif in your screenshot, seems it falls back to sans-serif font.

Oh, I see it. Sorry for my lack of sensitivity in fonts and characters. Now finally I know what's wrong and may be able to fix it.
