### ISSUE TITLE
Implement UI for V5

### ISSUE THREAD

**Issue by wongchito** [railmapgen/rmg#200]
Use the latest MUI to implement a modern UI for V5

**Comment by thekingofcity** [comment]
So for local development, which URL should be used to access V5? Tried http://localhost:3000/RailMapGenerator/v5/shmetro and http://localhost:3000/v5/RailMapGenerator/shmetro

UAT should be https://wongchito.github.io/uat-rail-map-generator/v5/mtr without a doubt.

**Comment by wongchito** [comment]
RMG V5 is LIVE now! 🎉
