### ISSUE TITLE
关于不同版本线路终点站牌不同

### ISSUE THREAD

**Issue by Thomastzc** [railmapgen/rmg#247]
双终点的默认样式应该是以逗号分隔，2020新样式才是将两个终点名称上下放置

**Comment by XHG78999** [comment]
您好，

请提供现实照片以证明您的观点。

XHG78999

**Comment by thekingofcity** [comment]
> 顺带一提两行终点站的格式是不是应该属于2020新风格？

_Originally posted by @thekingofcity in https://github.com/wongchito/RailMapGenerator/issues/83#issuecomment-8

当时修改后有询问过你的意见，看来是这样的。我也找到了sh时的实景图：

![](https://pic4.zhimg.com/80/v2-2df5e4bff1344cf3ce33a4093ea13767_1440w.jpg)

> 10、11 号线的主支线都将两个车站并排写，用逗号隔开，但这个逗号很违和，英语部分的逗号后面还没加空格。

感谢知乎作者[GlenXoseph](https://www.zhihu.com/people/glen-xu)在[上海地铁的导向标识演化 3](https://zhuanlan.zhihu.com/p/57368457)下的资料。

目前的打算是终点站画布区分`sh`和`sh2020`分别实现主支线的终点站样式。

**Comment by XHG78999** [comment]
也许我们应该新开一个字段@thekingofcity？毕竟由于申通过于懒（，很多车站是sh/sh2020混合，特有特性最好独立。

**Comment by XHG78999** [comment]
11号线有这类混合，direction是sh但是railmap是sh2020（江苏路）

**Comment by thekingofcity** [comment]
> 11号线有这类混合，direction是sh但是railmap是sh2020（江苏路）

direction指？有无实景图片呢？

**Comment by XHG78999** [comment]
逗号分隔+锯齿

**Comment by XHG78999** [comment]
好吧，毕竟兼容性要紧，不然要真这么迫真的话那么我们还要做贴纸（逃

**Comment by thekingofcity** [comment]
在环线的 2835403 中被修复，抱歉当时未同步至此issue中。
