### ISSUE TITLE
Project of modifying/generating RMG parameters

### ISSUE THREAD

**Issue by wongchito** [railmapgen/rmg#25]
@wongchito BTW I am working on a simple project that directly modify/generate the .json of RMG in order to deal with complex lines conveniently. It may use some of your templates, especially color templates. I wonder if there are any limits when I use them.

_Originally posted by @Rongronggg9 in https://github.com/wongchito/RailMapGenerator/issues/4#issuecomment-604631298_

**Comment by wongchito** [comment]
Could you please provide more details about the project. (You may edit the issue directly. )

You may want to check the type of `RMGParam` defined in `/src/types/app.d.ts`. However, it is not completed so I've used index signatures in it.

**Comment by Rongronggg9** [comment]
Python 实现，命令行操作，主要针对网页编辑线路的一些不便而编写，只设计为处理广州地铁风格。


## 计划实现的功能
* 转换使用其他地铁系统风格的换乘站类型到广州地铁风格支持的类型
* 批量添加换乘线路
  * 可直接从线路色模板里读取并使用线路名称 
    * 需要用到 RMG 的线路色模板，因此需要知道所允许的使用方式
  * 创建/使用自己的线路色模板
  * 从线路图 JSON 文件中导出所有使用的线路色参数 (颜色及中英文名称)
* 将现有的直线线路转换成支线成环形式
  * 可选择线路「折叠」(分支) 的位置
  * 如果可能，按照换乘站的换乘线路数量计算可能的最优折叠处，使得所需的画布高度最小
* 以更简洁而快速的方式添加车站
  * 更符合逻辑
    * 在 RMG 里按照原顺序添加车站的最简单方法是：先添加最后一个车站，然后再重复向这个车站之前添加车站 (因为每次添加车站时的定位车站不会自动定位到上一个添加的车站)
  * 减少操作次数
    * 默认生成的名字实际上使得使用鼠标时需要额外增加一个选中操作，使用键盘时需要额外退格
    * 弹出编辑车站详情的对话框后焦点不在车站名称处，需要点按 6 次 Tab 才能定位到车站名称的输入框
* 删除车站
  * 单个删除
  * 传入列表删除
  * 区间删除
* 移动车站
  * 移动单个车站
  * 移动区间
  * 移动区间成为支线


## 可能不会实现的功能
* 英文支持 (不熟悉地铁相关词汇)
* RMG 计划实现或改善的功能


该项目已经完成一部分，但由于精力有限，不太可能在近期内完成，预计会在完成部分关键功能后创建 repo 。
_比较惭愧的是，名字没有想好。_

**Comment by wongchito** [comment]
> - 可直接从线路色模板里读取并使用线路名称
>   - 需要用到 RMG 的线路色模板，因此需要知道所允许的使用方式

Please refer to [README of colours](../tree/master/src/panels/colour-diag/colours/) or simply checkout one of the `.ts` files. (They're no longer JSON files but TS (which are complied and minified) to reduce data transferred and improve loading speed for mainland Chinese users. )

I did ever think of adding this feature but I didn't find out an effective way to implement this due to multi-language problems. 

> - 创建/使用自己的线路色模板
> - 从线路图 JSON 文件中导出所有使用的线路色参数 (颜色及中英文名称)

These are really good suggestion and could be added to RMG (not recently). 

> - 将现有的直线线路转换成支线成环形式

There're some discussion in [#24](https://github.com/wongchito/RailMapGenerator/issues/24#issuecomment-602026635) as well. 

> - 更符合逻辑
>   - 在 RMG 里按照原顺序添加车站的最简单方法是：先添加最后一个车站，然后再重复向这个车站之前添加车站 (因为每次添加车站时的定位车站不会自动定位到上一个添加的车站)

I had an idea of re-writing the station-adding-dialogue, with perhaps some diagrams showing where the new station will be, since the current dialogue is dedicated for MTR style and the description in the selectors may not be appropriate for Guangzhou Metro and Shanghai Metro styles. 

Regarding to your suggestion, this relates to how the dialogue is triggered, which leads to another thought of mine -- re-design the `Stations` panel. (But I have no idea how the new design should be. ) 

> - 减少操作次数
>   - 默认生成的名字实际上使得使用鼠标时需要额外增加一个选中操作，使用键盘时需要额外退格
>   - 弹出编辑车站详情的对话框后焦点不在车站名称处，需要点按 6 次 Tab 才能定位到车站名称的输入框

I did aware of these issues and I will try to improve the dialogue. I also suffered from this issue since I have to make templates to test the functionality : ). 

> - 删除车站
> - 移动车站

These requires solid knowledge of graph theory so I may not be able to finish these in RMG.
