### ISSUE TITLE
一些对于线路图的建议Some suggestions for wiring diagram

### ISSUE THREAD

**Issue by OrdinaryRUNYING** [railmapgen/rmg#274]
1.（bug）以港铁风格的时候线路图会有当前站点显示（黑框），一般情况下黑框宽度和文字长度差不多，但时有黑框过宽的时候（特别是重新导入后，一般出现在起点终点站）
![rmg 9d7x 彭漠村 Pengmo_Village_353174608866894_edit_353204619844281](https://user-images.githubusercontent.com/101465504/158022844-b13c6487-990e-4be4-9f1a-5ad00dea3d45.png)
![rmg 9d7x 彭漠村 Pengmo_Village_edit_353192950249434](https://user-images.githubusercontent.com/101465504/158022849-f940199e-f210-4b94-8ceb-4d42329fcadd.png)
2（意见）希望能够在广铁&港铁中增加一个“无当前站”或“示意图”之类意思的按键，使线路图可以不显示当前站并显示全线（如下为示意图）
![1647093569521_gaitubao_1600x600](https://user-images.githubusercontent.com/101465504/158023006-853c7135-a6a6-4f4d-b1ca-f23cab80dfc0.png)
以上图片内容与现实无关

1. (Bug) in the MTR style, the route map will display the current station (black box). Generally, the width of the black box is about the same as the length of the text, but sometimes the black box is too wide (especially after re import, it usually appears at the starting and terminal stations)
2. 2 (opinion) I hope to add a button with the meaning of "no current station" or "schematic diagram" in Guangzhou Railway & Hong Kong Railway, so that the line diagram can not display the current station and display the whole line (the following is the schematic diagram)

The above picture content has nothing to do with reality. The translation comes from Baidu

**Comment by wongchito** [comment]
@OrdinaryRUNYING 你好，

1. 港鐵風格中車站名稱黑色背景之闊度乃因應文字闊度計算所得，時常會因目標字型未完成下載而導致計算錯誤。我們已嘗試多種方法令其在字型載入成功後再次計算闊度，但仍無法適應各種網絡及各種平台之狀況。若閣下發現黑色背景之闊度計算有誤，我們建議閣下修改車站名稱再改回原本之名稱，或切換當前車站，以觸發其闊度重新計算。同時，我們亦會繼續嘗試修復該問題。
2. 多謝閣下提出之意見。我們目前專注於第5代產生器之開發工作，在此之後，我們會考慮加入該功能。

再次多謝閣下使用路線圖產生器及提出寶貴之意見。

**Comment by OrdinaryRUNYING** [comment]
> @OrdinaryRUNYING 你好，
> 
> 1. 港鐵風格中車站名稱黑色背景之闊度乃因應文字闊度計算所得，時常會因目標字型未完成下載而導致計算錯誤。我們已嘗試多種方法令其在字型載入成功後再次計算闊度，但仍無法適應各種網絡及各種平台之狀況。若閣下發現黑色背景之闊度計算有誤，我們建議閣下修改車站名稱再改回原本之名稱，或切換當前車站，以觸發其闊度重新計算。同時，我們亦會繼續嘗試修復該問題。
> 2. 多謝閣下提出之意見。我們目前專注於第5代產生器之開發工作，在此之後，我們會考慮加入該功能。
> 
> 再次多謝閣下使用路線圖產生器及提出寶貴之意見。

谢谢回复 这么晚辛苦了～

**Comment by OrdinaryRUNYING** [comment]
对了 希望在修改地铁线路和名称时“颜色库”中选择城市地铁的颜色时可以把地铁名称一同输入而不是显示“轉線” 很抱歉这么晚再次打扰(_ _)
By the way, I hope that when editing the subway's color and name, selecting the color of urban subway in the "color library", The system can automatically fill in the subway name instead of displaying "Line". I'm sorry to disturb you again so late (_ _)
The translation part comes from Baidu

**Comment by wongchito** [comment]
> 对了 希望在修改地铁线路和名称时“颜色库”中选择城市地铁的颜色时可以把地铁名称一同输入而不是显示“轉線” 

在第5代產生器中，該功能經己被提升，敬請期待 :)

**Comment by wongchito** [comment]
> 1.（bug）以港铁风格的时候线路图会有当前站点显示（黑框），一般情况下黑框宽度和文字长度差不多，但时有黑框过宽的时候（特别是重新导入后，一般出现在起点终点站）

Technical root cause:

`document.fonts.ready` is sometimes resolved before CSS files are actually loaded (lazy), especially when user change RMG style in app. https://github.com/railmapgen/rmg/blob/rmg-5.0.27/src/svgs/mtr/station-name/station-name.tsx#L17

Proposed fixes:

Check whether `FontFaceSet` in `document.fonts` contains the expected font faces when `document.fonts.ready` is resolved. If not, wait for a certain period of time and retry. 

e.g.: `document.fonts.forEach(fontFace => console.log(fontFace.family));`
