### ISSUE TITLE
Template of Qingdao Metro

### ISSUE THREAD

**Issue by linchen1965** [railmapgen/rmg#285]
[Qingdao metro.zip](https://github.com/wongchito/RailMapGenerator/files/8301947/Qingdao.metro.zip)
Templates of all operated Qingdao Metro lines expect Line 1. (A large part of current line 1 will belong to Line 7 in the future)

**Comment by thekingofcity** [comment]
Hi, steps 4 and 5 are required for a successful merge.

https://github.com/railmapgen/rmg/wiki/How-to-add-color-palette-and-line-templates#line-templates

**Comment by linchen1965** [comment]
> Hi, steps 4 and 5 are required for a successful merge.
> 
> https://github.com/railmapgen/rmg/wiki/How-to-add-color-palette-and-line-templates#line-templates
[qingdao.txt](https://github.com/railmapgen/rmg/files/8456592/qingdao.txt)
Finished.

**Comment by thekingofcity** [comment]
They are updated in 8eb53cc. Thanks for your contribution!
