### ISSUE TITLE
【新线路图】多伦多地铁线路

### ISSUE THREAD

**Issue by 52PD** [railmapgen/rmg#299]
[Toronto Subway Lines.zip](https://github.com/wongchito/RailMapGenerator/files/8367170/Toronto.Subway.Lines.zip)
线路名字和所有模版我都打包在里面了（所有线路和车站中文名均参考自[维基百科](https://zh.wikipedia.org/zh-cn/%E5%A4%9A%E5%80%AB%E5%A4%9A%E5%9C%B0%E9%90%B5)）

然后我发现现在生成器里面多伦多地铁的颜色模版是没中文名的，所以如果可以的话颜色模版也补一下中文吧（中文名参考我发的这个压缩包里面就行）

**Comment by thekingofcity** [comment]
对于境外的线路，我在考虑有没有可能只填写英文？还是说对于现有支持的风格来说，只有英文会显得突兀？

**Comment by 52PD** [comment]
> 对于境外的线路，我在考虑有没有可能只填写英文？还是说对于现有支持的风格来说，只有英文会显得突兀？

我自己拿吉隆坡单轨试了一下，确实有点突兀（一串中文后突然只接英文确实比较怪）😂
![rmg rul5 Bukit_Bintang](https://user-images.githubusercontent.com/98044618/163834081-5c62e184-34e4-43ac-9283-665a3688495f.png)

**Comment by thekingofcity** [comment]
好的，那我们就原样合入吧

**Comment by thekingofcity** [comment]
更新于 4ed5e50，感谢您对项目的支持与贡献！
