### ISSUE TITLE
上海地铁4号线 2018版

### ISSUE THREAD

**Issue by kongxia114** [railmapgen/rmg#302]
由于无法 修改线路样式
[上海地铁4号线.zip](https://github.com/wongchito/RailMapGenerator/files/8438962/4.zip)

**Comment by Yexiaowei11** [comment]
尺寸出现一点问题.

**Comment by Yexiaowei11** [comment]
修改后的最后
版本
[上海地铁 4.zip](https://github.com/wongchito/RailMapGenerator/files/8438985/4.zip)
本

**Comment by thekingofcity** [comment]
2018版与当前项目中自带的模板有什么区别呢，烦请告知，谢谢您对项目的支持与贡献！

**Comment by 52PD** [comment]
检查了一下，你这个基本是不可能过的😂，错误太多了。

首先线路没成环这个我就不多说了（V5预览版是可以做环线的）
然后实在是不能理解为什么所有线路的中文名都只剩一个数字了？😂
（当然这些还不算上有两个“上海体育馆”站的bug）

> 2018版与当前项目中自带的模板有什么区别呢，烦请告知

然后就跟@thekingofcity 说的一样，即使去掉上面出现的这些错误，你这个跟现在V5里面预设的上海4号线模版也是重复的啊（甚至你这个版本还没V5里面预设的版本新）
