### ISSUE TITLE
UAT换乘线路编辑面板中两个”中文名称“而不是”英文名称“

### ISSUE THREAD

**Issue by 20110620bobby** [railmapgen/rmg#308]
![网页捕获_9-4-2022_15625_uat-railmapgen github io](https://user-images.githubusercontent.com/99967255/162560951-d79af08f-b2ca-4eec-9484-ef9825774b37.jpeg)

**Comment by wongchito** [comment]
感謝 @20110620bobby 指出。該翻譯問題現已更正，並將於近期發佈至UAT環境。多謝閣下的支持。
