### ISSUE TITLE
[V5 相关]话说V5里面关闭上海地铁风格的站台编号选项怎么没了

### ISSUE THREAD

**Issue by 52PD** [railmapgen/rmg#309]
![Screen Shot 2022-04-09 at 10 37 47 AM](https://user-images.githubusercontent.com/98044618/162578871-00408777-de30-4a1a-b6a4-ce2f76cdca2a.png)
如标题。话说这是没做完还是忘做了啊？😂
（补个V3上这个选项的位置防止作者找不到：![Screen Shot 2022-04-09 at 10 40 08 AM](https://user-images.githubusercontent.com/98044618/162578957-a1997133-b794-45fb-8976-280be6037f25.png)）

**Comment by thekingofcity** [comment]
之后不会有打开关闭站台编号的开关了，只需要将字段内容清空就不会显示了。感谢您及时指出问题并汇报🎉
