### ISSUE TITLE
【功能建议】1个小bug和1个建议功能

### ISSUE THREAD

**Issue by e233-1000** [railmapgen/rmg#326]
做环线的时候突然遇到一个bug。原本的环形线路在增加了一个站后变成了一个伪6字形线
<img width="501" alt="微信图片_20220426084812" src="https://user-images.githubusercontent.com/104121702/165197231-05e0144b-ce1e-4553-bbf6-ab1f8f0c9702.png">
希望作者有空能修复这个bug！
第二个是关于6字形线路的建议。有很多线路是像上面那种的6字形线路，希望作者增加一个6字形线路的功能，否则很多线路的模板做不了。望作者大大重视！

**Comment by XHG78999** [comment]
漏洞复现+1。应该是加站时没有重新计算路径导致的，具体我问一下@thekingofcity

**Comment by thekingofcity** [comment]
花了两个晚上重写了一下环线的站点xy计算和环线线路计算，希望新的版本在解决此问题的同时没有引入其他问题。

![image](https://user-images.githubusercontent.com/3353040/165774398-f85035f7-10ea-46ab-9c97-d0a12fd989bb.png)

顺带，我还放宽了底部站点数至少为1的限制，0也被允许选择了。

![image](https://user-images.githubusercontent.com/3353040/165774446-f2bb4cc9-5ea2-4cbe-8e22-99231248a881.png)

感谢您对项目的支持与建议，有支线的环线参见 #333。
