### ISSUE TITLE
北京地铁各个颜色参考值

### ISSUE THREAD

**Issue by beijing-subway** [railmapgen/rmg#330]
3号线： #c63042
12号线：#844121
13B线：#ff9e00
18号线：#082484/b50010
20号线：#84d7ad
22号线：#e7aeb5
28号线：#395521
30号线：#52c7ef
31号线：#7ba6de
32号线：#5ac363
M101线：#00ba8c
M102线：#4aaaf7
M103线：#9479ce
M104线：#848284

**Comment by thekingofcity** [comment]
嗨，有关北京地铁颜色的数值可以加入 #227 讨论，谢谢您对项目的支持！

**Comment by linchen1965** [comment]
这几条线路的颜色应该都没有定下来吧
