### ISSUE TITLE
【问题修复】关于环线支线的几个bug

### ISSUE THREAD

**Issue by e233-1000** [railmapgen/rmg#336]
昨天做了大江户线，发现支线bug很多。
1.支线的终点站后面居然接上了主线的站
![rmg 2SEtP8 光が丘 Hikarigaoka](https://user-images.githubusercontent.com/104121702/166082971-d45f71c4-3679-4c81-8d9f-743dcb82d27c.png)
<img width="595" alt="微信截图_20220430081818" src="https://user-images.githubusercontent.com/104121702/166082984-d9068e74-65fb-45c9-9123-de572bca22a0.png">
如图所示，光丘是支线的终点站，后面居然接上了主线的东新宿站。
2.无法显示支线
这个昨天已经反馈过了，是一个大工程

希望作者大大修复一下bug！

**Comment by e233-1000** [comment]
@thekingofcity @wongchito

**Comment by 52PD** [comment]
> 支线的终点站后面居然接上了主线的站

你是不是新建支线的时候支线范围就没选对？如果你设支线的时候把范围设在支线起点到“路線右端”（如下图1）的话是不可能出现支线终点后接主线车站这种bug的（如下图2，这里用的预设模版中的上海5号线）
![Screen Shot 2022-04-30 at 11 14 03 AM](https://user-images.githubusercontent.com/98044618/166111496-5d4802c1-c034-4029-88ac-e859d2e3d9db.png)
![rmg 951r 闵行开发区 Minhang_Development_Zone](https://user-images.githubusercontent.com/98044618/166111520-1c532931-2016-49d1-8920-4d8268f61300.png)

> 无法显示支线
这里基本可以确认你当时设支线的两端设错了。上海地铁风格的线路支线只有在支线两端都接入主线且当前车站不在支线上的时候会发生支线线路不显示的bug（如下图3和图4，这里用的预设模版中的港铁东铁线，注意当前车站在主支线上不同车站的区别）。（不过这个也是V3时期就有的老bug了，希望@thekingofcity 还是尽早修复一下吧）
![rmg 7gy7 火炭 Fo_Tan](https://user-images.githubusercontent.com/98044618/166111762-1b575ef5-5f9e-4e00-821e-37310063c1f6.png)
![rmg hybz 馬場 Racecourse](https://user-images.githubusercontent.com/98044618/166111769-af361925-c29b-4513-b80e-cc262f2825c3.png)

**Comment by e233-1000** [comment]
> > 支线的终点站后面居然接上了主线的站
> 
> 你是不是新建支线的时候支线范围就没选对？如果你设支线的时候把范围设在支线起点到“路線右端”或者“路線左端”（如下图1）的话是不可能出现支线终点后接主线车站这种bug的（如下图2，这里用的预设模版中的上海5号线） ![Screen Shot 2022-04-30 at 11 14 03 AM](https://user-images.githubusercontent.com/98044618/166111496-5d4802c1-c034-4029-88ac-e859d2e3d9db.png) ![rmg 951r 闵行开发区 Minhang_Development_Zone](https://user-images.githubusercontent.com/98044618/166111520-1c532931-2016-49d1-8920-4d8268f61300.png)
> 
> > 无法显示支线
> 
> 这里基本可以确认你当时设支线的两端设错了。上海地铁风格的线路支线只有在支线两端都接入主线且当前车站不在支线上的时候会发生支线线路不显示的bug（如下图3和图4，这里用的预设模版中的港铁东铁线，注意当前车站在主支线上不同车站的区别）。（不过这个也是V3时期就有的老bug了，希望@thekingofcity 还是尽早修复一下吧） ![rmg 7gy7 火炭 Fo_Tan](https://user-images.githubusercontent.com/98044618/166111762-1b575ef5-5f9e-4e00-821e-37310063c1f6.png) ![rmg hybz 馬場 Racecourse](https://user-images.githubusercontent.com/98044618/166111769-af361925-c29b-4513-b80e-cc262f2825c3.png)

我选的是到线路右端，但还是发生了bug。
如图所见，您用的是默认样式，而我用的是2020年样式，可能bug是因此产生的

**Comment by thekingofcity** [comment]
有关环线支线的问题参考 #333，我们不会解决任何尚未受支持功能的问题，谢谢。
