### ISSUE TITLE
关于环线的建议

### ISSUE THREAD

**Issue by beijing-subway** [railmapgen/rmg#339]
北京地铁10号线是一个很长的，站很多的环线，目前只有上海地铁能生成环线，这样就会出现问题：
![1651404044192](https://user-images.githubusercontent.com/104498315/166143678-f7647d50-9c8b-41db-9eab-ce295e13e34e.jpg)
可以看出，字与字重叠了，只要将下面向上移动就可以，但生成器没有这个功能，如果把所有站都放在上面的线上的话，又显得非常难看，所以建议添加一个像支线间距的功能，就是环线上下线的间距，选择固定哪条线，移动哪条线。

**Comment by 52PD** [comment]
我这里用了一下预设的上海地铁4号线的图试了一下，同样会发生底部字重叠的问题
然而5.0刚发布那时画布高度设到600以上后是没这个问题的，所以说这应该是最近的更新后新出现的bug😂
![Screen Shot 2022-05-01 at 11 41 12 PM](https://user-images.githubusercontent.com/98044618/166181645-e75c518d-4e69-483b-aa57-a3c9b2147d98.png)

**Comment by thekingofcity** [comment]
这个是#337更新后引入的问题，已修复于5.0.23，谢谢建议✨
