### ISSUE TITLE
【BUG】问题修复：带支线的环线（6字形线）

### ISSUE THREAD

**Issue by e233-1000** [railmapgen/rmg#347]
刚刚在修正自己做的大江户线，发现了一些bug
[大江戸線.zip](https://github.com/railmapgen/rmg/files/8629749/default.zip)
（大江户线原稿，供作者与下面的反馈互相参考）

1.
我新建了一条从都厅前到线路右端的支线。如图所见，都厅前是支线和主线的分歧站。都厅前进入支线后第一站应该是西新宿五丁目站
<img width="598" alt="微信截图_20220505163407" src="https://user-images.githubusercontent.com/104121702/166889798-25d22456-a96b-495e-986a-082b5a08bcc7.png">
但是线路图的效果预览却显示下一站是终点光丘站（这里的支线应该是从左往右看而不是从右往左看，推测原因在此，但方向设为向左以后bug仍然存在，可能需要增加新功能）
<img width="145" alt="微信截图_20220505163723" src="https://user-images.githubusercontent.com/104121702/166890238-731354eb-1753-4622-a9f9-64a8190ce40e.png">

2.
还是那条支线。当把终点光丘设为当前站时，发现前面还有站（新宿站，是都厅前在主线的后一站）
<img width="597" alt="微信截图_20220505163743" src="https://user-images.githubusercontent.com/104121702/166891123-c077927d-e00f-4932-8de7-5abf9b05c5b3.png">
<img width="608" alt="微信截图_20220505163814" src="https://user-images.githubusercontent.com/104121702/166891140-d0915827-7b16-4df7-8fed-0c60465c9d3b.png">

@thekingofcity @wongchito 希望两位作者大大尽快修复这个bug！

**Comment by 52PD** [comment]
这里你说的两个bug我都自己试了一下。

第一个在支线页面中点开路线段设置后再点翻转整条线路，这样都厅前接的第一个支线车站就是西新宿五丁目站而不是光丘站。

第二个确实需要修复一下。这里我搭配最近更新的上海3/4号线的模版试了一下，同样出现了江杨北路站（3号线起点站）的上一站接了东安路站（4号线的站）这种神奇bug。

（顺带吐槽一下，如果是单纯的上海地铁风格的bug单独艾特thekingofcity就行，wongchito只负责整个项目以及港铁和广州地铁风格的编程和维护）

**Comment by e233-1000** [comment]
> 第一个在支线页面中点开路线段设置后再点翻转整条线路，这样都厅前接的第一个支线车站就是西新宿五丁目站而不是光丘站了。

这个解决方案我试过一遍，结果这样新bug诞生了：如您的图所见，新宿站因为换乘太多以至于部分换乘线路被挤了出去。高度改成1400、1600都试过，站点的高度会随着画布高度而改变。您可以再把我的原作的高度改变试试还会不会有类似的bug @52PD 
如果真是这样，建议作者 @thekingofcity 增加一个像支线间距一样的环线的两线间距。毕竟遇到这种情况如果是正常的主线可以调整画布高度，支线可以调整支线间距，普通环线可以通过修改上下左右的参数。但带支线环线没法修改参数，也没法用调整画布高度的功能调整，这是就需要一个可以调整上下间距的功能了。

**Comment by e233-1000** [comment]
不过我发现了一种解决方法：
如图，默认的支线是往左的
<img width="421" alt="微信截图_20220506080355" src="https://user-images.githubusercontent.com/104121702/167045929-ae8a9a26-b87c-4d7c-abc5-976102af0b98.png">
不论是到线路左端还是到线路右端，支线都会往左。
建议作者大大可以把环线最上面一端设为只有一个站（也就是主支分歧站）然后到线路左端向左，线路右段向右。
或者有几个站都无所谓，但要保证支线能向右，这样也可以，否则向左的话会默认为线路从右到左，然而大江户线是先走环线再进入支线的。 @thekingofcity

**Comment by thekingofcity** [comment]
> 新宿站因为换乘太多以至于部分换乘线路被挤了出去

这个确实，但实际上在非环线的线路图上添加过多的换乘车站也会导致换乘线路被挤出，这个问题在非环线上没有那么严重的原因大致是因为线路以底端对齐，但实际上确实存在。

> 增加一个像支线间距一样的环线的两线间距

是一个好建议。

> 当把终点光丘设为当前站时，发现前面还有站

我会去检查一下的。

> 否则向左的话会默认为线路从右到左，然而大江户线是先走环线再进入支线的。

没有太理解您的意思，能指出实际的运行情况和图中显示的运行情况的区别吗？

**Comment by e233-1000** [comment]
> 没有太理解您的意思，能指出实际的运行情况和图中显示的运行情况的区别吗？

实际情况是：列车从都厅前出发，先进入主线中的新宿西口、开往饭田桥，两国方向，六本木方向；兜一圈从新宿站再次进入都厅前。不过第二次进入都厅前后应该进入支线，进入西新宿五丁目。图中的支线是向左的支线，此处改为向右的支线更为妥当。
我的意思是希望环线支线不光可以向左，还可以向右。设置的时候增加的支线如果是线路左端~分歧站支线就向左，分歧站~线路右段就向右，更为妥当以及方便。
本人有的时候表达不清楚，望作者大大谅解！ @thekingofcity

**Comment by 52PD** [comment]
> 我的意思是希望环线支线不光可以向左，还可以向右。

这个我感觉可以考虑一下，毕竟非环线线路设支线说能控制支线走向的话环线设支线确实可以考虑也包括这个功能（不过我个人感觉这个工程量估计会有点大，如果比较难的话我觉得开发者还是不要考虑这个点了（毕竟现在的设定也不是不能看））

**Comment by thekingofcity** [comment]
> 实际情况是：列车从都厅前出发，先进入主线中的新宿西口、开往饭田桥，两国方向，六本木方向；兜一圈从新宿站再次进入都厅前。不过第二次进入都厅前后应该进入支线，进入西新宿五丁目。图中的支线是向左的支线，此处改为向右的支线更为妥当。
我的意思是希望环线支线不光可以向左，还可以向右。设置的时候增加的支线如果是线路左端分歧站支线就向左，分歧站线路右段就向右，更为妥当以及方便。

![Inkedrmg UJKLGR 新宿西口 Shinjuku-nishiguchi_LI](https://user-images.githubusercontent.com/3353040/167257576-edb200d9-3061-4e9f-9d80-d7d8450cf33b.jpg)

不知道将方向置为左后能不能满足这一实际运行情况？

要我说来，相比非环线的确定方向，circle in directed graph会复杂很多。但还好目前没有计算也没有展示车站是否为前方站或已通过站，所以实际上你可以认为线路的运行方式是 _任意_ 的或 _未定义_ 的。

**Comment by thekingofcity** [comment]
> > 新宿站因为换乘太多以至于部分换乘线路被挤了出去
> 
> 这个确实，但实际上在非环线的线路图上添加过多的换乘车站也会导致换乘线路被挤出，这个问题在非环线上没有那么严重的原因是因为线路以底端对齐，但实际上确实存在。
> 
> > 增加一个像支线间距一样的环线的两线间距
> 
> 是一个好建议。
> 
> > 当把终点光丘设为当前站时，发现前面还有站
> 
> 我会去检查一下的。
> 
> > 否则向左的话会默认为线路从右到左，然而大江户线是先走环线再进入支线的。
> 
> 没有太理解您的意思，能指出实际的运行情况和图中显示的运行情况的区别吗？
> 
> 除此之外，现有的UI有一个小问题，在只有一条环线的时候应该允许用户调整bottom factor。临时解决方法可以先调整参数后再添加支线。我会在之后修复这个问题。

这些问题都已在上述commit中被修复。
