### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by kqburjso** [railmapgen/rmg#353]
导入配置文件后不能增加车站，且车站列表中会有和站名牌中不一样的字

**Comment by 52PD** [comment]
你不放图的话真的很难理解到底有什么bug。😓
（第一个我试了一下，并没有出现你说的问题。第二个不放图的话真的看不出有什么问题。）

**Comment by thekingofcity** [comment]
嗨，由于没有更多的信息提供，我们将关闭此问题。欢迎在拥有更多信息时重新打开此问题或新开一个问题，谢谢。
