### ISSUE TITLE
【港鐵】關於港鐵線路圖出站換乘的新bug和一個建議

### ISSUE THREAD

**Issue by 52PD** [railmapgen/rmg#355]
先說bug吧
如圖，最近的RMG更新後位於終點站的出站換乘的線路直接歪掉了😂
![MTR Railmap Bug](https://user-images.githubusercontent.com/98044618/168410276-8875b0ae-878b-405b-b2df-d09ec387b20b.png)
（這裡用的預設的東鐵線模版）

然後呢就是在想，之後的更新要不要把港鐵的出站換乘跟上海地鐵的出站換乘分開掉，畢竟港鐵風格下的出站換乘是去就近車站換換乘（比如荃灣線尖沙咀站出站去尖東站換乘屯馬線），而上海地鐵風格下的出站換乘只是付費區外換乘（比如上海火車站從1號線換3/4號線），但車站還是同一個車站。🤔
（個人感覺好像上海地鐵的出站轉乘（比如換金山鐵路和磁浮線）跟港鐵風格的出站換乘好像更像一些。當然因為我不是上海人也不在上海所以可能會有誤解😂）

**Comment by wongchito** [comment]
Hi @52PD ,

針對第1點，作為出站轉車站之終點站之圖示現已修復。感謝回報問題。

針對第2點，想了解 @thekingofcity 之意見。

**Comment by 52PD** [comment]
> 針對第2點，想了解@thekingofcity 之意見。

没问题，毕竟他是上海地铁风格的作者嘛。👌

**Comment by thekingofcity** [comment]
关于第二点，虽然出站换乘的实际情况在不同城市不同，但对于文字即 **出站换乘** **Out-of-Station interchange** 来说应该是一致的。我能想到的问题应该只有在两个风格中切换时，虽然是同样内容但含义不同这一种情况了。对于这种情况，如果修复方案是切换时修改存档的话感觉就很麻烦了。所以如果只是这个问题的话我不太想进行修改，用户应该需要理解并修改风格中一些微小的不同。当然如果我的理解有任何不准确的地方欢迎指出。

**Comment by 52PD** [comment]
> 关于第二点，虽然出站换乘的实际情况在不同城市不同，但对于文字即 **出站换乘** **Out-of-Station interchange** 来说应该是一致的。我能想到的问题应该只有在两个风格中切换时，虽然是同样内容但含义不同这一种情况了。对于这种情况，如果修复方案是切换时修改存档的话感觉性价比就很低了。所以如果只是这个问题的话我不太想进行修改，用户应该需要理解并修改风格中一些微小的不同。当然如果我的理解有任何不准确的地方欢迎指出。

确实，如果修改难度太大那还是算了。而且第二点括号那里我对照了一下英文版界面，好像也跟港铁不太符合（毕竟出站转乘目前是Out-of-system interchange，这反而又跟港铁的车站转车站不同了（毕竟这种换乘仍然是在港铁系统范围中，并不像上海火车站换乘金山铁路那种是从上海地铁系统转到了金山铁路市郊系统中））

**Comment by XHG78999** [comment]
所以这又涉及到在各个样式之间的特有字段转换问题。比如把上海的直达车转到广州，应该是会先弹出一个弹窗说“如果转换，那么作品中的xxxxx特性将被清除”这样更好。

**Comment by thekingofcity** [comment]
> 毕竟出站转乘目前是Out-of-system interchange，这反而又跟港铁的车站转车站不同了（毕竟这种换乘仍然是在港铁系统范围中

所以其实港铁的出站换乘和上海地铁的出站换乘其实都是同一系统内稍有距离的车站间的换乘？唯一的区别在于换乘车站是否同名？

> 所以这又涉及到在各个样式之间的特有字段转换问题。比如把上海的直达车转到广州，应该是会先弹出一个弹窗说“如果转换，那么作品中的xxxxx特性将被清除”这样更好。

如果含义像上述解释中基本一致的话，就不涉及这个问题了。在rmg的开发过程中，我们尽量是保证同样字段在不同风格中的一致（即如果含义不一致我们将单独开风格相关的字段）。这会有助于用户在不同风格中的切换。

> 确实，如果修改难度太大那还是算了。

但对于仅有微小含义差别的字段，我个人认为修改的优先级不够高。我们还有很多更重要的功能，将这些完成会更多的提升用户的体验。

**Comment by 52PD** [comment]
> 所以其实港铁的出站换乘和上海地铁的出站换乘其实都是同一系统内稍有距离的车站间的换乘？唯一的区别在于换乘车站是否同名？

这个我其实觉得还是问一下@wongchito 会稳妥一些吧🤔不过我去B站对比了一下（上海地铁是7号线长清路站换乘13号线长清路站，港铁是荃湾线尖沙咀站换乘观塘线尖东站）感觉确实是这种

**Comment by thekingofcity** [comment]
> > 所以其实港铁的出站换乘和上海地铁的出站换乘其实都是同一系统内稍有距离的车站间的换乘？唯一的区别在于换乘车站是否同名？
> 
> 这个我其实觉得还是问一下@wongchito 会稳妥一些吧🤔不过我去B站对比了一下（上海地铁是7号线长清路站换乘13号线长清路站，港铁是荃湾线尖沙咀站换乘观塘线尖东站）感觉确实是这种

如果真是如此，我感觉单纯在上海风时隐藏一下车站名即可。

**Comment by wongchito** [comment]
> > 所以其实港铁的出站换乘和上海地铁的出站换乘其实都是同一系统内稍有距离的车站间的换乘？唯一的区别在于换乘车站是否同名？
> 
> 
> 
> 这个我其实觉得还是问一下@wongchito 会稳妥一些吧🤔不过我去B站对比了一下（上海地铁是7号线长清路站换乘13号线长清路站，港铁是荃湾线尖沙咀站换乘观塘线尖东站）感觉确实是这种

港鐵有3種出站轉乘，

- 尖沙咀-尖東：出閘（非付費區），均為地鐵系統
- 中環-香港：不出閘（付費區），均為地鐵系統
- 九龍/柯士甸-香港西九龍：出閘，不同系統

上海或廣州之出站轉乘，事實上並不符合香港任何一種。🤔

**Comment by 52PD** [comment]
> 港鐵有3種出站轉乘，
> 
> - 尖沙咀-尖東：出閘（非付費區），均為地鐵系統
> - 中環-香港：不出閘（付費區），均為地鐵系統
> - 九龍/柯士甸-香港西九龍：出閘，不同系統
> 上海或廣州之出站轉乘，事實上並不符合香港任何一種。🤔

soga，我還以為是類似的呢😂（畢竟像上海的長清路的7號線轉13號線跟尖沙咀-尖東真的很像，都是要出閘-出站-進站-進閘這種（不過我看尖沙咀到尖東是直接有個地下換乘道連著），而且都是刷公交卡/八達通的乘客在30分鐘內換乘會當作一程計這種）

**Comment by XHG78999** [comment]
> > > 所以其实港铁的出站换乘和上海地铁的出站换乘其实都是同一系统内稍有距离的车站间的换乘？唯一的区别在于换乘车站是否同名？
> > 
> > 
> > 
> > 这个我其实觉得还是问一下@wongchito 会稳妥一些吧🤔不过我去B站对比了一下（上海地铁是7号线长清路站换乘13号线长清路站，港铁是荃湾线尖沙咀站换乘观塘线尖东站）感觉确实是这种
> 
> 港鐵有3種出站轉乘，
> 
> - 尖沙咀-尖東：出閘（非付費區），均為地鐵系統
> - 中環-香港：不出閘（付費區），均為地鐵系統
> - 九龍/柯士甸-香港西九龍：出閘，不同系統
> 
> 上海或廣州之出站轉乘，事實上並不符合香港任何一種。🤔

未来上海的普通市域铁路系统和金山铁路估计会出现港铁的状况（金山铁路和沪杭普速共线只能单独收钱）

**Comment by 52PD** [comment]
> 港鐵有3種出站轉乘，
> 
> * 尖沙咀-尖東：出閘（非付費區），均為地鐵系統
> * 中環-香港：不出閘（付費區），均為地鐵系統
> * 九龍/柯士甸-香港西九龍：出閘，不同系統
> 
> 上海或廣州之出站轉乘，事實上並不符合香港任何一種。🤔

我之后又去对比了一下，目前个人感觉虽然说上海地铁的出站转乘和港铁虽然有些不同，但事实上是非常相似的。
比如港铁的柯士甸-香港西九龍（出閘，不同系統）和尖東-尖沙咀（出閘，均為地鐵系統）：
![Screen Shot 2022-05-16 at 9 40 23 PM](https://user-images.githubusercontent.com/98044618/168712039-b79fac27-fcc3-4034-b1b7-f150ee5d64f4.png)
转换成上海地铁后大概就像这个样子：
![Screen Shot 2022-05-16 at 9 40 30 PM](https://user-images.githubusercontent.com/98044618/168712294-e5d4f170-40be-486a-b723-5234b12cb6ef.png)

同样的，上海地铁的7号线长清路-13号线长清路（均為上海地鐵系統）和浦东国际机场-磁浮机场（不同系統）：
![Screen Shot 2022-05-16 at 9 50 21 PM](https://user-images.githubusercontent.com/98044618/168712371-29b47b25-1581-4d92-ad68-59337790b2bb.png)
反过来这两个也可以转换成港铁样子：
![Screen Shot 2022-05-16 at 9 49 16 PM](https://user-images.githubusercontent.com/98044618/168712664-dedbde55-8eb5-4c2e-bf81-c91ddea08f85.png)

也就是说港铁的同系统出闸换乘跟上海地铁的出闸换乘类似（唯一区别就是港铁是不同站换乘，上海地铁是相同站换乘），而港铁的不同系统出闸换乘跟上海地铁的不同系统转乘就基本是一样的了（都是不同系统不同站换乘，顺带说一下1号线上海南站转金山铁路上海南站其实也是不同系统不同站转乘（地铁上海南站≠国铁上海南站））。

**Comment by thekingofcity** [comment]
感谢对比，如果如你所说港铁和上海风基本一样的话，那就没有修改的明显必要了。如果你有具体的建议，欢迎回复，没有的话直接关闭讨论即可 。

**Comment by 52PD** [comment]
> 感谢对比，如果如你所说港铁和上海风基本一样的话，那就没有修改的明显必要了。如果你有具体的建议，欢迎回复，没有的话直接关闭讨论即可 。

好呢，我这边没什么问题了

**Comment by 52PD** [comment]
> 感谢对比，如果如你所说港铁和上海风基本一样的话，那就没有修改的明显必要了。如果你有具体的建议，欢迎回复，没有的话直接关闭讨论即可 。

好吧。。这issue我又重开了😓

刚刚才发现一个问题。虽说港铁和上海风的出站换乘基本一样，但目前生成器里面港铁风是不会显示出站转乘（即出闸不同系统换乘）的（上面例子中上海风的转乘磁浮线能在港铁中显示是我把这条线挪到了出站换乘中才实现显示的，而港铁里面的换乘高速铁路在上海风里面变成“转乘高速铁路”也是靠把这条线挪到出站转乘中才实现的）

so，那个@wongchito 话说让港铁能显示出站转乘这个不知道能不能实现啊🤔（虽然我知道这个其实跟港铁现在写进出站换乘后关掉付费区换乘的显示效果重复了）。当然如果这个功能觉得没必要的话那就还是算了。

**Comment by wongchito** [comment]
> so，那個@wongchito 話說讓港鐵能顯示出站轉乘這個不知道能不能實現啊🤔（雖然我知道這個其實跟港鐵現在寫進出站換乘後關掉付費區換乘的顯示效果重復了）。當然如果這個功能覺得沒必要的話那就還是算了。

在RMG設計多種風格相互切換之時，已考慮到各公司風格稍有不同，無法完全做到無修改切換。這包含轉車站設定、路線圖垂直方向位置、支綫間距等。

對於轉車站分類及設定異同之問題，個人想法如下：

1. 「同站轉車」、「出站轉車」、「系統外轉車」，若各公司對車站分類規則不儘相同，RMG則優先按照各風格作圖時所需之元素作出分類，以做到側邊欄設定應用至路線圖時最合乎用家直觀感受。
  - 上海地鐵風格之「出站轉車」表示車站轉乘路線上需展示「僅限公共交通卡」提示，「系統外轉車」表示車站轉乘路線旁需展示「轉乘xx線」提示。
  - 港鐵風格之「出站轉車」，表示車站圖示以兩個圓形/圓角矩形展示，兩個圖形間用實線或虛線連接，取決於轉車通道是否位於付費區。由於港鐵暫不存在包含付費區及非付費區之大型轉車站組合，從而不存在需以三個圓形展示轉車站之情況，因此RMG暫不會為港鐵風格啓用「系統外轉車」欄位。
  - 由於廣州地鐵風格無明確區分各類轉車站，其將會展示來自設定檔3種類別之轉乘路線索

2. 隨着各城市地鐵線網之發展以及平面設計之提升，上述規則亦會相應作出調整

**Comment by 52PD** [comment]
> 由於港鐵暫不存在包含付費區及非付費區之大型轉車站組合，從而不存在需以三個圓形展示轉車站之情況，因此RMG暫不會為港鐵風格啓用「系統外轉車」欄位。

確實有這個問題，尤其是出現當某個車站有兩條線路出站換乘（一個位於同系統，一個位於不同系統，且兩條換乘線路都不在同一車站）或者兩條出站換乘線中只有一個付費區內換乘的情況下（不過國內和港澳台的地鐵線我好像還沒見過有上述這兩種奇葩換乘的😂）。（雖然可以像現在港鐵用優先級覆蓋的方式（比如當有個站有一個出站換乘線路和一個站內換乘線路那種，我記得目前是會優先只顯示出站換乘那條線），但這個估計很難😂）

**Comment by thekingofcity** [comment]
我已隐藏上海风格中站外或系统外换乘时车站名称的控件，上海风格中暂无此种情况，也并不会因为数据的修改而变化生成图。

**Comment by wongchito** [comment]
我亦同時隱藏廣州地鐵風格中轉車站名稱之欄位。
