### ISSUE TITLE
Deploy to other server to make the speed fast

### ISSUE THREAD

**Issue by XHG78999** [railmapgen/rmg#356]
You know, that the speed of github in mainland is very very bad. As we don't update v5 to gitlab, many users say that they cannot use this because some chunk timeout.

We should add to deploy other platform that it is fast in mainland, like surge.sh , to the deploy action.

**Comment by thekingofcity** [comment]
Users are advised to use the offline build of RMG at the [Release Page](https://github.com/railmapgen/rmg/releases). If there is no release for a long time, you are welcome to open an issue to request a new release. Currently, the release is triggered manually. Comment more if you have other situations where the offline build won't work.

**Comment by wongchito** [comment]
RMGv3 was released to GitLab pages and was deployed to BitBucket pages for testing. We should consider cleaning up those pages or release RMGv5 to those instances to avoid confusion.

**Comment by wongchito** [comment]
- [ ] Deploy entire RMG family to GitLab Pages
- [ ] Update banner for V3 RMG

**Comment by wongchito** [comment]
RMG family is deployed to Bitbucket pages now (https://railmapgen.bitbucket.io)
