### ISSUE TITLE
共线段问题

### ISSUE THREAD

**Issue by Thomastzc** [railmapgen/rmg#367]
当我打开
![image](https://user-images.githubusercontent.com/73764348/169736722-e91d15ea-79f2-448f-a78c-3367c72aaed7.png)
时，会显示四号线的终点站牌，而在3号线和共线段区间无法正常显示该区段的终点站牌，共线段终点站牌如下：
![a401ec13ad89794741330b08f834efcb_watermark_l](https://user-images.githubusercontent.com/73764348/169737331-13cacdac-abac-4163-95b1-758eeac8743f.jpg)
而3hao'xain号线单线区间又是不同的站牌，其图片如下：
![d64cc32dcc8aee7f6aced1a1f525a2e0_watermark_l](https://user-images.githubusercontent.com/73764348/169737166-9bd06e21-9b9b-40e2-b0e9-f4ff981da179.jpg)
嗯……而宝山路站和虹桥路站的分叉站，站名牌上有3号线和4号线的标识
![4084c07899bb463d5f2563f8e15d1bc1_watermark_l](https://user-images.githubusercontent.com/73764348/169737477-473c702d-a87a-4bbc-8fae-1e4ed175917b.jpg)
类似于这样……再扯一句，11号线嘉定新城站的分叉呈90°直角：
![e45a88a19ff22c024007852bec8ef49f_watermark_l](https://user-images.githubusercontent.com/73764348/169737586-4d4da58a-57bc-4d21-ae5a-f1ed24c15377.jpg)
类似于这样
还有10号线的站点号这些的，不知道有没有计划呢？
![260006041f5d790c7bf343ba3131f1d0_watermark_l](https://user-images.githubusercontent.com/73764348/169737755-fe4b6fb8-e1be-4044-ac61-89147630561e.jpg)
![bdbde8038ea6e903e723777e3afbf99a_watermark_l](https://user-images.githubusercontent.com/73764348/169737765-f4bb34fa-3441-4376-bcef-0049a8494b4f.jpg)
![e907684cdd07d577f7ea58016af51913_watermark_l](https://user-images.githubusercontent.com/73764348/169737789-217ae459-cc61-463e-abca-ea1824d08adf.jpg)
![7a3890c90c35818f61b07434a3031771_watermark_l](https://user-images.githubusercontent.com/73764348/169737797-0bfdb787-6498-4680-8dfb-9ec1f3cb818f.jpg)
嗯，大约就这些了

**Comment by Thomastzc** [comment]
哦还有，4号线非共线段，有三号线的那条黄线，具体图片我这暂时没有

**Comment by Jay20081229** [comment]
不错，就是这个问题，我在共线教程中要反映的

**Comment by Thomastzc** [comment]
什么教程？？？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "railmapgen/rmg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月23日(星期一) 下午3:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [railmapgen/rmg] 共线段问题 (Issue #367)





 
不错，就是这个问题，我在共线教程中要反映的

**Comment by 52PD** [comment]
> 共线段终点站牌如下：

帮你换张更清晰的，图源[https://m.weibo.cn/status/4440344063735939](url)：
![0063BuxHgy1g93bkpvo3uj33401r07wj](https://user-images.githubusercontent.com/98044618/169898031-a2250814-ace0-49b4-ab94-b1e4876fad31.jpg)

> 嗯……而宝山路站和虹桥路站的分叉站，站名牌上有3号线和4号线的标识

这个我觉得有必要加上。@thekingofcity 你怎么看？

> 还有10号线的站点号这些的，不知道有没有计划呢？

10号线站点编号已经在弄了，具体过程在#291 里面

**Comment by 52PD** [comment]
刚刚又发现一个可以考虑调整的：注意@Thomastzc 发的长江南路站和宝山路站的线路图，里面的“列车运行方向”旁的箭头是空心的，而不是非共线线路那种直接采用线路颜色

**Comment by XHG78999** [comment]
不好意思我鸽了很久（
目前在做啦，但是共线段怎么显示不好说，现在功能勉强能用，后面针对环线可能会再适配一下

**Comment by Thomastzc** [comment]
谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "railmapgen/rmg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月24日(星期二) 凌晨4:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [railmapgen/rmg] 共线段问题 (Issue #367)





  
共线段终点站牌如下：
  
帮你换张更清晰的，图源https://m.weibo.cn/status/4440344063735939：
 
  
嗯……而宝山路站和虹桥路站的分叉站，站名牌上有3号线和4号线的标识
  
***@***.*** 你怎么看？
  
还有10号线的站点号这些的，不知道有没有计划呢？
  
10号线站点编号已经在弄了，具体过程在#291 里面
