### ISSUE TITLE
关于两个”左侧支线“的问题

### ISSUE THREAD

**Issue by Jay20081229** [railmapgen/rmg#370]
为什么到现在都两个”左侧支线“呢？关键是，不止上海地铁风格有这个问题，就连港铁、广州地铁风格也都有这个问题。
语言为English时：
![屏幕截图 2022-05-24 120127](https://user-images.githubusercontent.com/59323889/169946580-931e5246-cf40-44c7-a8b5-677c1b631cee.png)

语言为简体中文时：
![屏幕截图 2022-05-24 120254](https://user-images.githubusercontent.com/59323889/169946611-e0fa0d4b-9a9b-4afd-8464-6a1dabc6b455.png)

语言为繁體中文时：
![屏幕截图 2022-05-24 120528](https://user-images.githubusercontent.com/59323889/169946709-61fca0e9-cbe7-452b-bb08-f6b22390f461.png)

能否把下面那个”左侧支线“改为”右侧支线“呢？
另外，原作者是否不允许我去制作新模板后上传了呢？麻烦快点解释清楚 @wongchito

**Comment by wongchito** [comment]
你好 @Jay20081229 ，

關於第一點，感謝回報該問題，我們會儘快修復標題文字。

關於第二點，請閣下參照[Wiki](https://github.com/railmapgen/rmg/wiki/How-to-add-color-palette-and-line-templates)並將相關路綫範本上傳至[RMG Templates](https://github.com/railmapgen/rmg-templates)，多謝。

**Comment by Jay20081229** [comment]
Thank you!
