### ISSUE TITLE
上海地铁风格大站快车和仅有的系统外换乘站之间字体存在侵入

### ISSUE THREAD

**Issue by rainydew** [railmapgen/rmg#380]
![NE L0%MH)J3INETVVP IUK9](https://user-images.githubusercontent.com/40389473/170888429-e617f7b3-9ee4-4ab3-932f-e22f8760529a.png)
大站快车且仅有系统外换乘的车站，会出现换乘信息侵入线路的情况
猜测因上海地铁刚好没有这两种同时存在的情况而没能兼容

**Comment by XHG78999** [comment]
应该是计算坐标时没有做特判。

**Comment by thekingofcity** [comment]
嗨，感谢您对项目的支持与建议。新的修复已经发布，希望解决了所有的出站换乘和系统外换乘的情况。

![image](https://user-images.githubusercontent.com/3353040/174320351-66fbfaf1-4b6d-412a-96da-e4c8ecbbd04a.png)
![image](https://user-images.githubusercontent.com/3353040/174320387-82d00ae5-4c75-4296-a242-dd475b718221.png)
![image](https://user-images.githubusercontent.com/3353040/174320833-3a29f10b-67a5-47ef-bb83-4574735a5883.png)

**Comment by rainydew** [comment]
感谢大佬，我晚些就试下
