### ISSUE TITLE
关于“下载图像文件名对不上图片”的问题

### ISSUE THREAD

**Issue by Jay20081229** [railmapgen/rmg#383]
我首先下载所有车站，然后打开陈仓枢纽这个车站图像，发现这实际上是西蜀广场站的线路图。
![屏幕截图 2022-06-02 111449](https://user-images.githubusercontent.com/59323889/171547729-ef656d75-a967-4df4-b849-c729363dfed1.png)
别的车站也有这个问题。
以下分别是线路图内容、站名牌、配置文件的压缩包：
[rmg.1号线.Line_1 (16).zip](https://github.com/railmapgen/rmg/files/8820929/rmg.1.Line_1.16.zip)
[rmg.1号线.Line_1 (17).zip](https://github.com/railmapgen/rmg/files/8820930/rmg.1.Line_1.17.zip)
[RMG_1654138539883.zip](https://github.com/railmapgen/rmg/files/8820932/RMG_1654138539883.zip)

@wongchito 请在下个版本时修复此问题！

**Comment by 52PD** [comment]
上海地铁风格的维护是@thekingofcity 负责的了。。。你应该找他才对😂（@wongchito 只负责整个程序和港铁与广州地铁风格的维护）

**Comment by wongchito** [comment]
> 上海地铁风格的维护是@thekingofcity 负责的了。。。你应该找他才对😂（@wongchito 只负责整个程序和港铁与广州地铁风格的维护）

下載圖像功能是共同使用的，所以 @thekingofcity 和我均應對其負責😃

**Comment by thekingofcity** [comment]
批量下载图像的功能之前由我魔改添加，但后来v5 @wongchito 也改过，所以是共同负责 🤣

**Comment by wongchito** [comment]
It's good to clarify the ownership of this feature. Close as dup #378 😃
