### ISSUE TITLE
换行符问题

### ISSUE THREAD

**Issue by xiaowu-PRC** [railmapgen/rmg#384]
![屏幕截图 2022-06-03 191646](https://user-images.githubusercontent.com/96490847/171843894-de04e50d-736d-49f8-8467-494287f27c6e.png)
上海地铁换行符在终点站站牌和当前站名牌会显示\，而不是隐藏

**Comment by rainydew** [comment]
有意思的是英文的换行符是ok的
导致我都没发现这个

**Comment by thekingofcity** [comment]
嗨，感谢您汇报的问题。换行符在之前的版本中仅支持英文，这是由于上海地铁目前仅有英文会有换行的情况。然而，不管在终点站画布和当前站画布中，都不存在中文换行的情况。但针对这个问题我仍然进行了换行符修复并隐藏，但不会新增任何换行的实际功能。

**Comment by XHG78999** [comment]
> 嗨，感谢您汇报的问题。换行符在之前的版本中仅支持英文，这是由于上海地铁目前仅有英文会有换行的情况。然而，不管在终点站画布和当前站画布中，都不存在中文换行的情况。但针对这个问题我仍然进行了换行符修复并隐藏，但不会新增任何换行的实际功能。你可以在5.2.10的版本中体验到最新的修复结果，谢谢。

那为什么之前的v4有啊（雾
