### ISSUE TITLE
增加馬場支綫

### ISSUE THREAD

**Issue by Solar0798** [railmapgen/rmg#397]
可唔可以生增馬場嘅支綫

**Comment by 52PD** [comment]
你說的是東鐵線往馬場的那條支線嗎？
如果是那條的話早就有了啊😓（紅圈圈起來的那部分）：
![rmg 2It3ab 金鐘 Admiralty](https://user-images.githubusercontent.com/98044618/177459025-7185fae2-e2f1-49c5-a068-f57aa45b0c13.png)

**Comment by wongchito** [comment]
Closed as no reply.
