### ISSUE TITLE
Text Alignment behaviour is not consistent across Safari and Chrome

### ISSUE THREAD

**Issue by wongchito** [railmapgen/rmg#400]
再补充一个：注意在Safari和Chrome上生成的广州地铁站名图的区别（上为Safari，下为Chrome）
![rmg l1mz 番禺广场 Panyu_Square-2](https://user-images.githubusercontent.com/98044618/178793385-8e3bd254-e35b-4e5b-9c41-e901843ab631.png)
![rmg l1mz 番禺广场 Panyu_Square (1)](https://user-images.githubusercontent.com/98044618/178793396-5b79d8a3-9762-4ef6-9810-ae9de230abf2.png)

_Originally posted by @52PD in https://github.com/railmapgen/rmg/issues/399#issuecomment-1183486705_

**Comment by wongchito** [comment]
@52PD Could you please check out to the UAT version (https://uat-railmapgen.github.io/rmg/gzmtr) and verify the change. Thanks!

<img width="956" alt="image" src="https://user-images.githubusercontent.com/9390786/179346998-cf57f31b-153e-44f1-9228-a0ad5853c7b2.png">

**Comment by 52PD** [comment]
@wongchito I just checked it, the the gap between Chinese and English station name finally looks good on Safari.
![rmg l1mz 番禺广场 Panyu_Square](https://user-images.githubusercontent.com/98044618/179362329-3a479ac8-f0ed-4ad3-9d94-5b33863b30e5.png)
![rmg l1mz 番禺广场 Panyu_Square (1)](https://user-images.githubusercontent.com/98044618/179362331-f358875f-3648-40fe-bf0d-f9cdb026ad6f.png)
Thank you!
