### ISSUE TITLE
Set default int_padding for new station

### ISSUE THREAD

**Issue by Solar0798** [railmapgen/rmg#404]
上海地鐵版本個路線走錯位，但係其他站都冇問題
![image](https://user-images.githubusercontent.com/108619591/180126287-1d5577f3-47a3-4c63-911c-7cbad3562cb8.jpeg)

**Comment by thekingofcity** [comment]
嗨，感谢汇报问题，方便保存存档后贴入本issue的回复框中吗？

**Comment by Solar0798** [comment]
即是把跑錯位嗰個檔案傳給你嗎？

**Comment by thekingofcity** [comment]
对的，可以直接拖到对话框中上传即可

**Comment by Solar0798** [comment]
我不會傳送存檔但我能把文字給你
{"style":"shmetro","svg_height":405,"padding":6,"y_pc":59.92,"branch_spacing":45,"theme":["hongkong","wrlkcr","#AC2571","#fff"],"direction":"r","current_stn_idx":"8gdz","platform_num":"1","stn_list":{"linestart":{"parents":[],"children":["l1mz"],"name":["路綫左端","LEFT END"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[]]},"services":["local"],"facility":"","num":"00","secondaryName":false,"loop_pivot":false,"one_line":true,"int_padding":355},"lineend":{"parents":["vee5","pnz7"],"children":[],"name":["路綫右端","RIGHT END"],"branch":{"left":["through","vee5"],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[]]},"services":["local"],"facility":"","num":"00","secondaryName":false,"loop_pivot":false,"one_line":true,"int_padding":355},"l1mz":{"parents":["linestart"],"children":["wsz9"],"name":["華富麗","Wah Fuli"],"branch":{"left":[],"right":[]},"num":"01","transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[]]},"services":["local","express"],"facility":"","secondaryName":false,"loop_pivot":false,"one_line":true,"int_padding":355},"iwf6":{"children":["6zjw"],"parents":["wsz9"],"name":["華富麗樂園","Huayui Paradise"],"branch":{"left":[],"right":[]},"num":"03","transfer":{"tick_direc":"r","paid_area":false,"osi_names":[],"info":[[["other","other","#AD6C3E","#fff","華橋綫","Huadia Line"]],[]]},"services":["local"],"facility":"","secondaryName":false,"loop_pivot":false,"one_line":true,"int_padding":355},"wsz9":{"name":["華南村","Huaver Village"],"secondaryName":false,"num":"02","services":["local"],"parents":["l1mz"],"children":["iwf6"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"aleo":{"name":["西門碼頭","West door pier"],"secondaryName":false,"num":"06","services":["local","express"],"parents":["o493"],"children":["_HsAZK"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["other","other","#AD6C3E","#fff","華橋綫","Huadia Line"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"o493":{"name":["恆域","Hanwick"],"secondaryName":false,"num":"05","services":["local","express"],"parents":["6zjw"],"children":["aleo"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["other","other","#AD6C3E","#fff","華橋綫","Huadia Line"],["other","other","#2c3f9b","#fff","華茘綫","Huali Line"]],[]],"tick_direc":"r","paid_area":true,"osi_names":[["Hi","Stn Name"]]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"6zjw":{"name":["西恆域門","West Hanwick Door"],"secondaryName":false,"num":"04","services":["local"],"parents":["iwf6"],"children":["o493"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"bddt":{"name":["四季","Four Seaaone"],"secondaryName":false,"num":"10","services":["local","express"],"parents":["g5sd"],"children":["av7f","oqod"],"branch":{"left":[],"right":["through","av7f"]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"g5sd":{"name":["大圍","Tai Wai"],"secondaryName":false,"num":"09","services":["local","express"],"parents":["kPQJgG"],"children":["bddt"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["other","other","#993921","#fff","屯利綫","Tunley  Line"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"f0ru":{"name":["京原","Kyohara"],"secondaryName":false,"num":"08","services":["local"],"parents":["bhuw"],"children":["kPQJgG"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"bhuw":{"name":["會展","Exhibition Centre"],"secondaryName":false,"num":"07","services":["local"],"parents":["_HsAZK"],"children":["f0ru"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"8gdz":{"name":["華倫路","Warren Road"],"secondaryName":false,"num":"13","services":["local"],"parents":["av7f","oqod"],"children":["76yy"],"branch":{"left":["through","av7f"],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"oqod":{"name":["華倫市","Warren"],"secondaryName":false,"num":"12","services":["local"],"parents":["bddt"],"children":["8gdz"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"av7f":{"name":["華倫都馬場*","Valention Racecourse*"],"secondaryName":false,"num":"12R","services":["local"],"parents":["bddt"],"children":["8gdz"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"pnz7":{"name":["華富城邊境管制站","Wah Fu City Border Control Point"],"secondaryName":["華富城口岸","Wah Fu City Port"],"num":"15P1","services":["local","express"],"parents":["76yy"],"children":["lineend"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["other","other","#ca423c","#fff","西區過境支綫","WDTB"]],[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"vee5":{"name":["      羅湖","Lo Wu"],"secondaryName":false,"num":"15P2","services":["local","express"],"parents":["76yy"],"children":["lineend"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"76yy":{"name":["華富城","Wah Fu City"],"secondaryName":false,"num":"14","services":["local","express"],"parents":["8gdz"],"children":["vee5","pnz7"],"branch":{"left":[],"right":["through","vee5"]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"_HsAZK":{"name":["京山","Cap Mountain"],"secondaryName":false,"num":"00","services":["local"],"parents":["aleo"],"children":["bhuw"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["hongkong","mol","#9A3820","#fff","屯利綫","Tunley Line"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":0},"kPQJgG":{"name":["華都西","Huadu West"],"secondaryName":false,"num":"00","services":["local"],"parents":["f0ru"],"children":["g5sd"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["hongkong","","#aaaaaa","#fff","",""]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":0}},"line_name":["華恆綫","Wan Han Line"],"psd_num":"1","line_num":"WH","info_panel_type":"gz1421","direction_gz_x":71.83,"direction_gz_y":82.54,"customiseMTRDest":{"isLegacy":false,"terminal":false},"svgWidth":{"destination":1700,"runin":2300,"railmap":5000,"indoor":3000},"notesGZMTR":[["*為特殊日子開放","*Open for special days",10.5,81.5,false],["R為馬場","R for Racecours",22.5,82,false],["P為邊境管制站","P for border control points",30,82,false]],"namePosMTR":{"isStagger":false,"isFlip":false},"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":0,"bottom_factor":1}}

**Comment by Solar0798** [comment]
[Uploading RMG_1658379097494.json…]()

**Comment by thekingofcity** [comment]
您好，拖动后需要等待一会儿上传完成再comment，上一条的内容无法被读取

**Comment by Solar0798** [comment]
他讀取不到

**Comment by Solar0798** [comment]
[Uploading RMG_1658379097494.json]()

**Comment by Solar0798** [comment]
好吧看來不能讀取

**Comment by Solar0798** [comment]
可以email給你嗎

**Comment by thekingofcity** [comment]
欢迎将json存档发至[3353040+thekingofcity@users.noreply.github.com](mailto:3353040+thekingofcity@users.noreply.github.com)

**Comment by 52PD** [comment]
> 好吧看來不能讀取

内个，你可以先打包成zip或者rar啥的再上传，这样就能读取了😂

**Comment by Solar0798** [comment]
那個海已經傳送電郵了你看看吧

**Comment by 52PD** [comment]
不過我想我已經知道問題在哪了。

你先點換乘線路有錯位的那個車站，然後注意一下編輯頁面（就點車站後右邊那個編輯區域）最下面的「車站名與換乘線路間的間距」是不是0，如果是0的話那就說明你在添加新車站後忘記調整了（這次更新後上海地鐵新添加的車站默認換乘線路標都為0，需要手動調整）。

下圖為我未對新增車站的換乘線路間距調整前的樣子（也就是默認為0）：
![Screen Shot 2022-07-21 at 10 55 53 AM](https://user-images.githubusercontent.com/98044618/180245792-472bf262-3359-476d-af84-68494d1dfec0.png)

**Comment by Solar0798** [comment]
Ok

**Comment by thekingofcity** [comment]
可能是转发有点问题，我还没有收到存档。不过应该是如 @52PD 所说的，创建新车站时使用了0作为车站名与换乘线路的间距。之后会有常见默认值的修复，敬请期待。

**Comment by Solar0798** [comment]
> 欢迎将json存档发至[3353040+thekingofcity@users.noreply.github.com](mailto:3353040+thekingofcity@users.noreply.github.com)

![image](https://user-images.githubusercontent.com/108619591/180335152-ddb96e3c-150e-4c34-98a2-03e005f574f6.jpeg)

**Comment by 52PD** [comment]
> ![image](https://user-images.githubusercontent.com/108619591/180335152-ddb96e3c-150e-4c34-98a2-03e005f574f6.jpeg)

你要不還是把檔案打包（rar或者zip都行）後再直接上傳（不要發郵箱）吧😓

**Comment by Solar0798** [comment]
> > ![image](https://user-images.githubusercontent.com/108619591/180335152-ddb96e3c-150e-4c34-98a2-03e005f574f6.jpeg)
> 
> 你要不還是把檔案打包（rar或者zip都行）後再直接上傳（不要發郵箱）吧😓

我還是放棄吧⋯⋯
