### ISSUE TITLE
Add apply all action to int_padding

### ISSUE THREAD

**Issue by Dingdong2334** [railmapgen/rmg#405]
![屏幕截图 2022-07-21 215808](https://user-images.githubusercontent.com/79365860/180232580-faac113c-2fc3-4fdc-a507-af8325c43581.png)

线路图刚创建编辑时换乘线路与站名的间距是适中正常的，
如果再次打开线路图，
换乘线路与站名的间距就会卡BUG，突然变得很远。

![屏幕截图 2022-07-21 215819](https://user-images.githubusercontent.com/79365860/180232598-f19b9496-e0ab-4567-8aac-2fc352e01031.png)

我查找了一下，
这里的“车站名与换乘线路间的间距”被统一调成了355，
不知道是何原因。

望解决，感谢！

> **线路JSON文件：**
[gz11.zip](https://github.com/railmapgen/rmg/files/9159969/gz11.zip)

**Comment by Dingdong2334** [comment]
您好！

![屏幕截图 2022-07-21 221024](https://user-images.githubusercontent.com/79365860/180234724-2f3fcf4b-4029-47a5-88a6-adf4b19156a6.png)

另外，我发现，
如果要使得站台屏蔽门的线路图看起来垂直间距合适，
那么车内线路图就会贴在一起，看起来很奇怪。
反之相同。

![屏幕截图 2022-07-21 221008](https://user-images.githubusercontent.com/79365860/180234764-32b945d5-957b-4797-89ad-a7091f1f1c52.png)

**Comment by thekingofcity** [comment]
嗨，感谢汇报问题。这可能是因为版本升级后默认给所有车站设置默认值导致的问题，需要您手动每个车站的换乘间距到一个合适的值，默认的环线模板250会是一个不错的值。如果在设置过间距后重新加载模板仍然被重设，欢迎再次汇报。

另：站台门路线图和车内路线图同一高度不合适的问题已知许久，在rmg尚未支持不同路线图不同高度前，您可以为其中之一调整合适高度后，生成图片，再调整高度到另一路线图合适的高度，谢谢。

**Comment by Dingdong2334** [comment]
您好！感谢您的解答！
请问可否在以后的版本中加入统一调整换乘间距的功能？
感谢！

**Comment by thekingofcity** [comment]
感谢建议，此功能已完成并发布。

**Comment by Dingdong2334** [comment]
感谢！
