### ISSUE TITLE
Dialogue fails to resize when browser zoomed

### ISSUE THREAD

**Issue by CrSjimo** [railmapgen/rmg#406]
There is a bug with  "Preview And Export" dialogue. If the browser window is zoomed in and then out back to 100%, its horizontal size will shrink. 

![2022-07-21 23-04-07](https://user-images.githubusercontent.com/35359408/180248023-be18d428-59df-4a2c-a94e-5f27ccdd2ea3.gif)

**Comment by thekingofcity** [comment]
Hi, thanks for the reporting. However, V3 is no longer maintained. Users are recommended to use the latest V5 at https://railmapgen.github.io/rmg/ where download process is updated.
