### ISSUE TITLE
关于站台门线路图无法正常显示的问题

### ISSUE THREAD

**Issue by feitongxiaok** [railmapgen/rmg#411]
如图。当显示“全部”时，站台门图无法显示，但其他图均可正常显示。而单独显示站台门板线路图时，仍无法显示。但用老版生成器打开新版生成器生成的jason文件时所有线路图均可正常显示，求解决，感谢！
![Screenshot_2022-07-30-07-47-10-070_com android browser](https://user-images.githubusercontent.com/110245355/181861725-12c661ca-f314-429a-9a08-8d8f374abbd9.jpg)
![Screenshot_2022-07-30-07-47-16-468_com android browser](https://user-images.githubusercontent.com/110245355/181861730-7eb181d9-20ee-410f-9c1e-46dd6b6cab05.jpg)

**Comment by 52PD** [comment]
so。。。出bug时你用的是什么浏览器？
你不说浏览器名称开发者也没法对阵下药啊😂（因为又不是所有手机浏览器上打开RMG都有你说的这个bug）

**Comment by thekingofcity** [comment]
应该是手机浏览器版本太低，建议使用最新的chrome或firefox浏览器，谢谢

**Comment by 52PD** [comment]
> 应该是手机浏览器版本太低

纠正一下，安卓的话主要问题其实跟浏览器版本没啥关系，大多还是跟浏览器内核（绝大多数安卓第三方浏览器用的都是安卓自带的webview内核，只有极少数用的是自家的内核（比如chrome和firefox）

**Comment by feitongxiaok** [comment]
当时我使用的是小米系统自带的浏览器
是不是用像谷歌，edge这种浏览器不会出这个毛病？似乎小米的浏览器并不好

**Comment by feitongxiaok** [comment]
用edge解决了，谢谢大佬们！
