### ISSUE TITLE
线路图做好了，网页出现问题

### ISSUE THREAD

**Issue by 2327464179** [railmapgen/rmg#413]
![网页捕获_14-8-2022_9461_railmapgen github io](https://user-images.githubusercontent.com/111209587/184519146-af09eb48-9f56-4e81-94f0-bc8ed478f19f.jpeg)
已经编辑好站名了，线路图突然没有了，刷新了好几次网页，还是出现错误，望尽快修复！！！

**Comment by thekingofcity** [comment]
你好，麻烦将存档和详细信息一并上传到这里

**Comment by 2327464179** [comment]
> 你好，麻烦将存档和详细信息一并上传到这里

https://railmapgen.github.io/rmg/

**Comment by 2327464179** [comment]
可能是浏览器的问题，Win10IE浏览器线路图就是打不开，换了谷歌浏览器可以打开了。
