### ISSUE TITLE
铁路线路图生成器删除站名出现问题

### ISSUE THREAD

**Issue by 2327464179** [railmapgen/rmg#414]
![屏幕截图 2022-08-14 162659](https://user-images.githubusercontent.com/111209587/184528872-cd553a60-bc13-40a0-8732-8efdff8bd875.png)
![屏幕截图 2022-08-14 162711](https://user-images.githubusercontent.com/111209587/184528874-76b8dfa4-f999-4b19-9546-e88466b3d97e.png)
![屏幕截图 2022-08-14 162721](https://user-images.githubusercontent.com/111209587/184528876-ff50ba70-db43-43ea-b602-5f122fa3f318.png)
大家去试试，当你快做完线路图，把最后一站删除，页面就会出现这种情况，真是气死我了，浪费了很多时间！！！望尽快修复！！！不是浏览器的问题！！！

**Comment by 2327464179** [comment]
各种浏览器都试过了，都是同样的问题——站名删除后，线路图消失，会出现这种情况……

**Comment by wongchito** [comment]
你好 @2327464179 ，

麻煩閣下點擊展開「詳細信息」並將其錯誤訊息貼上於此處，以便我們調查問題。如可能，請下載配置檔並於此上載，我們會進一步檢視該問題。

為你帶來不便，我們深表歉意。

**Comment by 52PD** [comment]
> 大家去试试

Safari和mac端的Chrome已经试过了，没出现你所说的bug

> 真是气死我了，浪费了很多时间！！！

这只是显示出了问题而已，你制作的线路图是仍然正常的，只要你没清过cookie的话通常刷新一下页面就能解决。实在不行你点“下载->配置文件”把你制作的线路图代码文件之后刷新页面再点“打开->上传配置文件“重新加载一遍刚才下载的线路图代码文件试试能不能解决。

**Comment by 52PD** [comment]
这里我自己模拟了一下你说的这个bug，如果是因为上面我说的原因导致的显示bug的话那报错的详细信息我就替你发在下面了。

TypeError: undefined is not an object (evaluating 'g[s===u.wA.left?"parents":"children"]')

p@https://railmapgen.github.io/rmg/static/js/runinGZMTR.b6fda8e8.chunk.js:1:2939
v@https://railmapgen.github.io/rmg/static/js/runinGZMTR.b6fda8e8.chunk.js:1:10104
Suspense
svg
c@https://railmapgen.github.io/rmg/static/js/AppRoot.52f9404c.chunk.js:1:9373
n@https://railmapgen.github.io/rmg/static/js/main.ecb4710f.js:2:2819
div
@https://railmapgen.github.io/rmg/static/js/main.ecb4710f.js:2:340422
@https://railmapgen.github.io/rmg/static/js/main.ecb4710f.js:2:152547
b@https://railmapgen.github.io/rmg/static/js/AppRoot.52f9404c.chunk.js:1:10563
div
@https://railmapgen.github.io/rmg/static/js/main.ecb4710f.js:2:340422
section
@https://railmapgen.github.io/rmg/static/js/main.ecb4710f.js:2:340422
@https://railmapgen.github.io/rmg/static/js/main.ecb4710f.js:2:152547
div
@https://railmapgen.github.io/rmg/static/js/main.ecb4710f.js:2:340422
@https://railmapgen.github.io/rmg/static/js/main.ecb4710f.js:2:152547
div
@https://railmapgen.github.io/rmg/static/js/main.ecb4710f.js:2:340422
@https://railmapgen.github.io/rmg/static/js/main.ecb4710f.js:2:152547
nr@https://railmapgen.github.io/rmg/static/js/main.ecb4710f.js:2:406584
div
@https://railmapgen.github.io/rmg/static/js/main.ecb4710f.js:2:340422
@https://railmapgen.github.io/rmg/static/js/main.ecb4710f.js:2:152547
er@https://railmapgen.github.io/rmg/static/js/main.ecb4710f.js:2:406350
pe@https://railmapgen.github.io/rmg/static/js/AppRoot.52f9404c.chunk.js:1:82816
n@https://railmapgen.github.io/rmg/static/js/main.ecb4710f.js:2:2819
Suspense
A@https://railmapgen.github.io/rmg/static/js/main.ecb4710f.js:2:742971
R@https://railmapgen.github.io/rmg/static/js/main.ecb4710f.js:2:742230
c@https://railmapgen.github.io/rmg/static/js/main.ecb4710f.js:2:735699
v@https://railmapgen.github.io/rmg/static/js/main.ecb4710f.js:2:199649
m@https://railmapgen.github.io/rmg/static/js/main.ecb4710f.js:2:136524
d@https://railmapgen.github.io/rmg/static/js/main.ecb4710f.js:2:340633
A@https://railmapgen.github.io/rmg/static/js/main.ecb4710f.js:2:309311
m@https://railmapgen.github.io/rmg/static/js/main.ecb4710f.js:2:200231
go@https://railmapgen.github.io/rmg/static/js/main.ecb4710f.js:2:266585
b@https://railmapgen.github.io/rmg/static/js/main.ecb4710f.js:2:733394
b

这里我模拟这个bug用的是生成器自带的广州地铁1号线的线路图，当前车站设定的为广州东站（广州1号线终点站），删除的车站也是广州东站。
[删除车站显示报错模拟用.json.zip](https://github.com/railmapgen/rmg/files/9335324/json.zip)

**Comment by wongchito** [comment]
多謝 @52PD 協調排查問題並提供臨時解決方法。我會嘗試儘快修復該問題。

**Comment by wongchito** [comment]
你好 @2327464179 ，

閣下所反映的問題已於最新版本中修復，用家將無法直接移除當前車站。取而代之的是，用家需將當前車站設定為其他車站後，再將原本車站移除。如閣下仍然開啟存在問題之檔案，可嘗試重新設定當前車站，並重新整理頁面。如問題持續發生，請重新開啟（Reopen）此Issue。

感謝閣下回報問題。
