### ISSUE TITLE
建议添加主题

### ISSUE THREAD

**Issue by beiguangrailtransit** [railmapgen/rmg#416]
铁路线路图生成器只有上海，广州，香港三个主题，希望添加更多，如苏州地铁 ，北京地铁等等。。。

**Comment by 52PD** [comment]
我估计这个建议会被拒掉吧。🤔

之前开发者在[#31 (comment)](https://github.com/railmapgen/rmg/issues/31#issuecomment-609608213)的回复如下：

> 1.线路图的风格只有香港、广州、上海，能不能考虑加入其它的风格？（如北京、西安、成都、重庆等）
> As an individual, I'm not able to maintain too many styles or features. Also, I'm not familiar with the transport systems in the cities other than where I live. So it maybe possible for me to add a style in the future if it has detailed design standards provided. From a more practical view, it would be better for you or others to contribute to this project. (We understand the relevant documentations are far from satisfying but we'll update it and provide as many help as we can.)

> 作為個人開發者無法同時兼顧過多風格或功能，同時亦不熟悉居住地以外的交通系統。因此我有可能在未來新增有完整設計標準的風格。但從實踐角度，由閣下或其他有志之士向該項目作出貢獻將會更好。（我們知道相關開發檔案未盡人意，但我們會持續更新它，亦會提供足夠的協助。）

**Comment by Harrislin22915** [comment]
请楼主在吗？

**Comment by thekingofcity** [comment]
如同2楼所回复的，受限于时间和精力，目前没有更多风格的开发计划。但欢迎您加入项目实现想要的风格，我们会提供一切帮助。

**Comment by 52PD** [comment]
> 请问楼主在吗？

不要问“请问楼主在吗”这种毫无意义的问题啊😂😂😂
