### ISSUE TITLE
Add New Style

### ISSUE THREAD

**Issue by kxztf123** [railmapgen/rmg#433]
Can you add new Style for Qingdao Metro？

**Comment by 52PD** [comment]
Sorry, based on developers' previous reply, the answer is No.

The reason was given in [#31 (comment)](https://github.com/railmapgen/rmg/issues/31#issuecomment-609608213):

> As an individual, I'm not able to maintain too many styles or features. Also, I'm not familiar with the transport systems in the cities other than where I live. So it maybe possible for me to add a style in the future if it has detailed design standards provided. From a more practical view, it would be better for you or others to contribute to this project. (We understand the relevant documentations are far from satisfying but we'll update it and provide as many help as we can.)
