### ISSUE TITLE
Unify isNumLine regex

### ISSUE THREAD

**Issue by 52PD** [railmapgen/rmg#434]
@thekingofcity 虽说在Slack讨论群那边我也发过了，不过我觉得这边还是也发一个比较合适😛
（其实这个建议我很早之前就想说了😂）

那么，最近我做线路图（北京的）的时候，我注意到上海地铁风格如果是字母开头线路的名称在终点方向站牌上的显示就跟数字开头线路一样的：
![Screen Shot 2022-09-13 at 11 08 29 AM](https://user-images.githubusercontent.com/98044618/189941000-fdc39ce9-78cd-4154-bb68-cd4ad837743c.png)
但到了线路图上就变成文字开头线路的显示格式了：
![Screen Shot 2022-09-13 at 11 09 02 AM](https://user-images.githubusercontent.com/98044618/189941120-9b8d9e08-247e-4fe5-9f01-e3c445b9a4f1.png)
感觉如果在识别到字母开头线路的名称时有两种风格的显示方式一个是不太统一，另一个就是在线路图上显示完整的“S1线”名称感觉真的很奇怪（如果线路图上像上海的“浦江线”那种显示完整名称倒没问题（毕竟官方风格），但完整显示“S1线”这种是真的怪）

所以我就在想如果可以的话，能不能把字母开头线路的名称显示方式统一一下（比如统一成方块里面只显示像“S1”这样的线路编号（我比较希望是这个））🤔

**Comment by thekingofcity** [comment]
嗨，感谢指出微小差别。已在测试环境更新，欢迎访问 https://uat-railmapgen.github.io/rmg/ 体验并验证最新的修改，是否常见的线路名都符合了预期。欢迎reopen这个issue如果你发现任何问题。
