### ISSUE TITLE
生产环境仍然被提示为测试环境

### ISSUE THREAD

**Issue by rainydew** [railmapgen/rmg#439]
![DQWQILY08OS%3DQZBJB7N9E](https://user-images.githubusercontent.com/40389473/191814712-ebded2fb-7030-4bcf-97dd-05f6759d1fb9.png)

如图，PRD已经是生产环境，但是仍然提示我该环境不稳定

**Comment by thekingofcity** [comment]
@wongchito looks like we need to set `popoverBody` to `undefined` in `<RmgEnvBadge />` if `environment` if PRD

**Comment by wongchito** [comment]
感謝 @rainydew 回報問題。

@thekingofcity Yes we need to update the implement in RMG. Nothing needs to be done in RMG-components though.
