### ISSUE TITLE
Rename items in localStorage

### ISSUE THREAD

**Issue by wongchito** [railmapgen/rmg#440]
To align with RMG family designs and for better controlling, we need to rename the items stored in localStorage.

**Comment by thekingofcity** [comment]
What's the new convention? I believe it would be better to also change before rmp release.

**Comment by wongchito** [comment]
Currently in rmg-runtime and rmg-home, items are stored with keys staring with app name: 

- `rmg-runtime__language`
- `rmg-home__openApps`

For RMG, I will use 'rmg' as the app name, such as `rmg__canvasScale` and `rmg__param`.

**Comment by thekingofcity** [comment]
Great, rmp is updated and following the new convention.
