### ISSUE TITLE
Show template author in a separate line

### ISSUE THREAD

**Issue by wongchito** [railmapgen/rmg#442]
Show template author in a separate line to avoid lengthy template name

Related issue: railmapgen/rmg-templates#46

<img width="458" alt="image" src="https://user-images.githubusercontent.com/9390786/192132296-09c7a45b-ad59-4eef-800d-0bd365833630.png">

**Comment by thekingofcity** [comment]
This looks great. What will be displayed if it is created by us? Corresponding GitHub username or Railmapgen project?

**Comment by wongchito** [comment]
> This looks great. What will be displayed if it is created by us? Corresponding GitHub username or Railmapgen project?

I prefer using our username.

There is another problem yet to be answered - If A created the template but B then updated a few lines (characters), shall we display A or B? The proposed new field is called `updatedBy`. (Can discuss further in railmapgen/rmg-templates#46)

**Comment by thekingofcity** [comment]
> There is another problem yet to be answered - If A created the template but B then updated a few lines (characters), shall we display A or B? The proposed new field is called updatedBy. 

Currently, I will update it to display B only if there is a station missing problem in the template. Otherwise, I will keep A for small tweaks like translation and transfer info.
