### ISSUE TITLE
Promote rmp in global alerts

### ISSUE THREAD

**Issue by thekingofcity** [railmapgen/rmg#445]
Say hi to Rail Map Painter! 🎉

https://railmapgen.github.io/rmp/

**Comment by Jay20081229** [comment]
请问那个地铁线路图绘制器如何反馈问题？ @thekingofcity

**Comment by wongchito** [comment]
> 请问那个地铁线路图绘制器如何反馈问题？ @thekingofcity 

你好 @Jay20081229 ! 歡迎前往 https://github.com/railmapgen/rmp/issues 提出你的建議或意見。
