### ISSUE TITLE
Line name of out-of-station interchange is overlapped by station name

### ISSUE THREAD

**Issue by Solar0798** [railmapgen/rmg#454]
![image](https://user-images.githubusercontent.com/108619591/194478492-300a3ea9-9d57-48d0-b93d-80178a7a1fc7.jpeg)

**Comment by 52PD** [comment]
看起来像是开发者没考虑过出现图中石涌站这种双换乘各只有一条线路换乘吧😂（毕竟港铁唯一的双换乘方式（站内和虚拟换乘）的终点车站（中环站）的虚拟换乘站（香港站）是两条线路（东涌线和机场快线））

**Comment by wongchito** [comment]
你好 @Solar0798 ！請問閣下想實現哪種轉綫模式呢？閣下現選擇了1個同站轉綫及1個出站轉綫，但未為同站轉綫加入路綫名稱及選擇顏色。

**Comment by Solar0798** [comment]
> 看起来像是开发者没考虑过出现图中石涌站这种双换乘各只有一条线路换乘吧😂（毕竟港铁唯一的双换乘方式（站内和虚拟换乘）的终点车站（中环站）的虚拟换乘站（香港站）是两条线路（东涌线和机场快线））那這有什麼方法修正

**Comment by Solar0798** [comment]
> 看起来像是开发者没考虑过出现图中石涌站这种双换乘各只有一条线路换乘吧😂（毕竟港铁唯一的双换乘方式（站内和虚拟换乘）的终点车站（中环站）的虚拟换乘站（香港站）是两条线路（东涌线和机场快线））

那可以怎樣修正

**Comment by 52PD** [comment]
> 那可以怎樣修正

这个你问问 @wongchito 吧😂

**Comment by 52PD** [comment]
> 你好 @Solar0798 ！請問閣下想實現哪種轉綫模式呢？閣下現選擇了1個同站轉綫及1個出站轉綫，但未為同站轉綫加入路綫名稱及選擇顏色。

我个人认为lz想要实现图上这种吧🤔（这里把中环-香港站换乘里面的机场快线暂时去了）
![Screen Shot 2022-10-07 at 10 28 26 PM](https://user-images.githubusercontent.com/98044618/194683610-a629da3f-c2d7-4ef3-b309-9064db071386.png)

**Comment by Solar0798** [comment]
> 你好 @Solar0798 ！請問閣下想實現哪種轉綫模式呢？閣下現選擇了1個同站轉綫及1個出站轉綫，但未為同站轉綫加入路綫名稱及選擇顏色。

兩種也是,就是「360」被遮住了

**Comment by wongchito** [comment]
> 
> 
> 
> 
> 
> 
> 
> 
> > 你好 @Solar0798 ！請問閣下想實現哪種轉綫模式呢？閣下現選擇了1個同站轉綫及1個出站轉綫，但未為同站轉綫加入路綫名稱及選擇顏色。
> 
> 
> 
> 兩種也是,就是「360」被遮住了

明白。由於該轉綫類型不存在於港鐵系統內，我們無法預測其展示樣式。針對這種情況，我們會考慮發佈一個修復版本，將轉乘路綫名靠左（右）對齊，以免文字被遮擋。

**Comment by wongchito** [comment]
![rmg HxZri_ 中環 Central](https://user-images.githubusercontent.com/9390786/197718658-2d1468b8-ce8e-42c9-8e6a-3489a41ce77c.png)
