### ISSUE TITLE
Unable to select line colour using colour codes on mobile devices

### ISSUE THREAD

**Issue by Transportation-master-kcl** [railmapgen/rmg#457]
This makes it impossible to choose the exact colour for the railway line on mobile devices, unless you import it from a save from RMG 0.5.3 or a save made with a computer.

**Comment by thekingofcity** [comment]
Hi, this is a known issue. See #399 Enhancement 2 and the reply from @wongchito is

> - [ ] Advanced colour picker
>     - This is not planned at the moment. We expect this to be implemented by each UA itself. 
>     - Safari iOS version is an example.
