### ISSUE TITLE
Cross-platform colour picker compatibility

### ISSUE THREAD

**Issue by wongchito** [railmapgen/rmg#460]
This issue is to analyse the compatibility of colour picker `<input type="color">` in mainstream browsers on different platforms. Implementing the V3-styled custom colour picker or not will be based on the result of this analysis. 

<img width="608" alt="image" src="https://user-images.githubusercontent.com/9390786/197014685-b9f16004-ec86-41f2-8ab5-b6ed90e7304f.png">

**Comment by wongchito** [comment]
## macOS

### Safari
<img width="699" alt="image" src="https://user-images.githubusercontent.com/9390786/197014985-1bd0e924-6aea-403d-862f-4f7843c2a87a.png">

### Chrome
<img width="456" alt="image" src="https://user-images.githubusercontent.com/9390786/197015252-4374304c-d751-4a9b-aaa5-d01d64b163df.png">

### Firefox
<img width="690" alt="image" src="https://user-images.githubusercontent.com/9390786/197015523-25dc4927-4a04-4abf-adbe-5a2521e44f5e.png">

**Comment by wongchito** [comment]
## iOS

### Safari
![image](https://user-images.githubusercontent.com/9390786/197016182-b2235a1e-2831-4395-9d21-dbc96618cd75.png)

### Chrome
![image](https://user-images.githubusercontent.com/9390786/197016297-8296d14a-ae47-4960-9655-231e2e23c8b7.png)

**Comment by thekingofcity** [comment]
## Windows

---

### Firefox
![image](https://user-images.githubusercontent.com/3353040/197207248-b41389fb-5675-41cc-b72d-0a8e4520ebec.png)

### Chrome
![image](https://user-images.githubusercontent.com/3353040/197207610-128464ce-92ea-4749-aa91-5cb7f38a5b00.png)
