### ISSUE TITLE
Unable to reuse the colour of recently used lines in 5.7.7

### ISSUE THREAD

**Issue by Transportation-master-kcl** [railmapgen/rmg#474]
In other versions, there was an option to use recently used lines' configuration (including colour). In the latest version however, users have to choose the colour for each interchange one by one.

**Comment by wongchito** [comment]
Hi @Transportation-master-kcl , 

We've just checked the latest version but we found that the colour picker and input autocomplete drop-down can be shown properly (see screenshots below). 

Could you please provide your operating system and browser for us to check further. Thanks!

![image](https://user-images.githubusercontent.com/9390786/202468174-6a80e7b0-9e70-4b30-b45f-e230c3bbdb59.png) 

![image](https://user-images.githubusercontent.com/9390786/202468278-0f6ce405-6373-4b29-94d0-f20b25834f1c.png)

**Comment by wongchito** [comment]
Hi @Transportation-master-kcl , 

We've just checked the latest version but we found that the colour picker and input autocomplete drop-down can be shown properly (see screenshots below). 

Could you please provide your operating system and browser for us to check further. Thanks!

![image](https://user-images.githubusercontent.com/9390786/202468174-6a80e7b0-9e70-4b30-b45f-e230c3bbdb59.png) 

![image](https://user-images.githubusercontent.com/9390786/202468278-0f6ce405-6373-4b29-94d0-f20b25834f1c.png)

**Comment by thekingofcity** [comment]
I believe he/she is referring to the recently used colors instead of the auto completion feature. It is available in V3 and helps users to select color with out typing and selecting one from the drop down list. I'm also looking forward to this feature. :)

**Comment by wongchito** [comment]
Track in railmapgen/rmg-palette#761
