### ISSUE TITLE
[bug] ”上海地铁”风格中，若英文线路名中开头字母是“L”，则会在站内线路图中显示为“Line+线路名”

### ISSUE THREAD

**Issue by suntrise** [railmapgen/rmg#489]
有个bug，铁路线路图生成器中”上海地铁”风格中，若英文线路名中开头字母是“L”，则会在站内线路图中显示为“Line+线路名”
广州地铁和港铁风格无此问题
![image](https://user-images.githubusercontent.com/89229642/211250094-0cb14ce4-7ec5-45fa-8459-f64da9582266.png)
![image](https://user-images.githubusercontent.com/89229642/211249182-89e9e95b-c75d-4444-9e04-063961e8181e.png)

**Comment by thekingofcity** [comment]
嗨，又修复了一个之前的修复引入的问题，图片来自Slack讨论 KevinZhang

![image](https://github.com/railmapgen/rmg/assets/3353040/e80d1521-7af4-4c38-98af-8243bf46b95d)
