### ISSUE TITLE
Allow importing project from external URL

### ISSUE THREAD

**Issue by wongchito** [railmapgen/rmg#492]
This is one of the tasks of railmapgen/rmg-templates#65.

A new query parameter (`/rmg/?external=https%3A%2F%2Fexample.com%2Ftest.json`) is added for loading RMG with specified project from external URL directly. The target server should have CORS enabled and the `JSON` file will be downloaded and converted to a local project (with a random ID). 

After a new template PR is created by bot, reviewers can verify the correctness of the uploaded templates by simply clicking the URL generated with the query parameter mentioned above.

**Comment by thekingofcity** [comment]
If our goal is to render a final picture for contributors to check whether their projects look good, we could use GitHub Actions to render all the canvas for us with the help of headless browsers (Selenium, etc) and upload the pictures in the PR. Then both contributors and maintainers can have a review without any rmg instance.
