### ISSUE TITLE
首都圈电铁线路名字错误问题，请求添加首都圈电铁4号线和水仁盆堂线

### ISSUE THREAD

**Issue by WOLFRAZOR** [railmapgen/rmg#501]
水仁盆堂线对应线路不对，应该是新盆堂线。

**Comment by WOLFRAZOR** [comment]
[4号线和水仁盆堂线站名牌图.zip](https://github.com/railmapgen/rmg/files/10709389/4.zip)
[首都圈电铁4号线和水仁盆堂线站台门路线图.zip](https://github.com/railmapgen/rmg/files/10709390/4.zip)

已经全部打包完毕。至于为什么4号线那里多了一个站，那个站是为了保持格式用的（不能删除，删除会破坏整个图）。因为首都圈电铁4号线另一端终点站就是乌耳岛（此站为水仁盆堂线仁川方向最后一个共线站）。

**Comment by WOLFRAZOR** [comment]
[4号线和水仁盆堂线.zip](https://github.com/railmapgen/rmg/files/10709475/4.zip)
这是配置。
![2023-02-09-14-38-33-015](https://user-images.githubusercontent.com/93996192/218147181-de7d76a1-4556-46ff-96fc-2fab0e84f709.jpg)
4号线图的在这，水仁盆堂忘记拍了。但我没记错。

**Comment by WOLFRAZOR** [comment]
首都圈电铁1号线和首尔地铁2号线路线情况特殊，无法使用现有绘制器绘出。
https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Seoul_Subway_Line_2_map.svg/1920px-Seoul_Subway_Line_2_map.svg.png

https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Seoul_Subway_Line_1_%28JPN%29.svg/2880px-Seoul_Subway_Line_1_%28JPN%29.svg.png

**Comment by 52PD** [comment]
有关线路模版的内容请移步此处：https://github.com/railmapgen/rmg-templates
