### ISSUE TITLE
请求添加首尔地铁屏蔽门的风格

### ISSUE THREAD

**Issue by WOLFRAZOR** [railmapgen/rmg#502]
图片如下（手机像素太差了，可能没办法拍的很清楚）：
![2023-02-09-19-20-45-385](https://user-images.githubusercontent.com/93996192/218271999-511d752e-2fa9-413b-92c5-d9dbd36955a4.jpg)
![20230206_155845](https://user-images.githubusercontent.com/93996192/218272005-bd16201e-4bbd-40f3-b188-3de269a78ff0.jpg)
![20230206_170140](https://user-images.githubusercontent.com/93996192/218272007-5ebbaee1-d3e8-4d9d-aeb5-53fa1ec119d4.jpg)
![IMG_2022-12-10-14-08-29-686](https://user-images.githubusercontent.com/93996192/218272009-49644349-489a-435e-89dc-a8ba9baf52d3.jpg)
![IMG_2022-12-10-14-08-43-108](https://user-images.githubusercontent.com/93996192/218272015-952f7ece-e410-4918-9ee9-005bdda4f82b.jpg)
![IMG_20220917_082809](https://user-images.githubusercontent.com/93996192/218272017-7d249b79-8744-4737-8432-d27fdb10b1fa.jpg)
![IMG_20220917_095559](https://user-images.githubusercontent.com/93996192/218272018-c87489c3-fedf-4ba7-a83a-2e939974e5e6.jpg)
![IMG_20220921_163837](https://user-images.githubusercontent.com/93996192/218272020-0ad620c4-e3c9-4304-90cc-5bc7c9722773.jpg)
![IMG_20230209_192424_295](https://user-images.githubusercontent.com/93996192/218272021-99dee528-fa02-4780-b082-2e44e6667868.jpg)

请开发者看一下是否能实现。
盼复
谢谢

**Comment by WOLFRAZOR** [comment]
![IMG_20221017_085814](https://user-images.githubusercontent.com/93996192/218272296-c2104020-a14b-42d6-bee5-f0f8db031ee4.jpg)
![2023-02-09-14-38-33-015](https://user-images.githubusercontent.com/93996192/218272298-464d28d9-75ca-4405-9d44-300c47e2de29.jpg)

顺便把屏蔽门外侧和线路图放一下。

**Comment by thekingofcity** [comment]
嗨，感谢对项目的支持与建议。有关新城市或线路风格实现，请参见[此位于#31中的回复](https://github.com/railmapgen/rmg/issues/31#issuecomment-609608213)，鉴于目前两位核心贡献者的时间与精力，短期之内应该不会有新的风格上线，谢谢理解。
