### ISSUE TITLE
韩语翻译完成

### ISSUE THREAD

**Issue by WOLFRAZOR** [railmapgen/rmg#504]
终于把这个做完了。文件在这：（Windows不要直接用记事本打开，请使用其他软件打开。macOS可以使用TextEdit直接打开）
[232322.txt](https://github.com/railmapgen/rmg/files/10759129/232322.txt)

这些都是用我的私人时间完成的。碰巧这几天休息，所以才做了那么多。

后面又要开始忙了，回复这些什么的不一定是马上有的。希望能得到谅解。

**Comment by thekingofcity** [comment]
嗨，感谢您的贡献，韩语翻译已上线 🎉
