### ISSUE TITLE
吉隆坡 巴生谷资讯需要更新

### ISSUE THREAD

**Issue by MASangys** [railmapgen/rmg#510]
目前查看的画布已经是有所更动，包括新地铁线开通以及部分站名更改。

**Comment by 52PD** [comment]
您好，有关线路模版有关的内容和问题请移步https://github.com/railmapgen/rmg-templates 。此处现只处理与RMG核心功能有关的问题。

此外，由于RMG中大部分模版并未我们负责制作而是有多位贡献者提供，如果您发现某个铁路线路的模版需要更新的话，您可以在https://github.com/railmapgen/rmg-templates 提交更新后的线路模版，不必单独发布issue告知我们。
