### ISSUE TITLE
Bump version after build

### ISSUE THREAD

**Issue by thekingofcity** [railmapgen/rmg#511]

**Comment by SMGDHHYF** [comment]
请问一下，能不能增加一个广州地铁风格的“车厢内线路图”谢谢你（不知道作者看不看得懂中文） @thekingofcity

**Comment by thekingofcity** [comment]
> 请问一下，能不能增加一个广州地铁风格的“车厢内线路图”谢谢你（不知道作者看不看得懂中文） @thekingofcity

嗨，已在 #508 中回复 :)
