### ISSUE TITLE
Suggestion: Font Size Scaling

### ISSUE THREAD

**Issue by HTG-YT** [railmapgen/rmg#526]
It would be nice if it would be possible to adjust the font size in a flexible manner without changing the resolution of the canvas.

**Comment by wongchito** [comment]
Hi @HTG-YT ,

Could you please provide more detail about the text you want to scale? As far as we concern, randomly scaling text may break the ratio between texts and other elements, and it requires more effort on adjusting the spacing and alignment of the texts.
