### ISSUE TITLE
关于支线的建议

### ISSUE THREAD

**Issue by polygon827** [railmapgen/rmg#562]
在RMG中，支线上是不能加入支线的
但在某些线路上，需要这个功能(MTR)
example： https://www.ratp.fr/plans-lignes/rer/a
仅为建议，本人对于代码“一窍不通”，望开发者采纳

**Comment by 52PD** [comment]
感觉支线上再建立支线这个应该不一定会接受吧，毕竟目前RMG上的三种风格对应的地铁系统（港铁、广州地铁和上海地铁）都没有出现过支线上再分支出支线的情况。

所以就上面提到的来讲，通过代码实现你的建议理应不难，但就无法找到任何考证资料的情况下估计实现不了😂

**Comment by thekingofcity** [comment]
> 通过代码实现你的建议理应不难

其实很难 🌚 我和chito在v5开发前讨论过这个问题，最后的结论是需要的精力与重写无异，在可见的未来估计不太会进行了 :(

**Comment by thekingofcity** [comment]
See #248
