### ISSUE TITLE
关于上海地铁线路图切换其他风格后终点站线路牌显示错误

### ISSUE THREAD

**Issue by kivenCRT** [railmapgen/rmg#565]
我准备做首都机场线的线路图上传，但是呢，遇到了一个问题，就是我试了港铁和广州地铁的风格后，上海地铁的终点牌显示错误，还请解决一下，非常感谢。我会把文件发过来，可以打开试试 [ TypeError: Cannot read properties of undefined (reading '0')      at se (https://railmapgen.github.io/rmg/assets/index-146c183a.js:1:3576)     at g     at ke (https://railmapgen.github.io/rmg/assets/index-146c183a.js:1:2353)     at svg     at W (https://railmapgen.github.io/rmg/assets/share-fbd51136.js:1:107)     at ye (https://railmapgen.github.io/rmg/assets/index-146c183a.js:1:1947)     at t (https://railmapgen.github.io/rmg/assets/index-b47975a7.js:1:110250)     at div     at https://railmapgen.github.io/rmg/assets/chakra-0b0a1fde.js:16:6186     at https://railmapgen.github.io/rmg/assets/chakra-0b0a1fde.js:16:132996     at https://railmapgen.github.io/rmg/assets/chakra-0b0a1fde.js:16:296899     at as (https://railmapgen.github.io/rmg/assets/app-router-1fb209cd.js:1:2978)     at div     at https://railmapgen.github.io/rmg/assets/chakra-0b0a1fde.js:16:6186     at https://railmapgen.github.io/rmg/assets/chakra-0b0a1fde.js:16:132996     at section     at https://railmapgen.github.io/rmg/assets/chakra-0b0a1fde.js:16:6186     at https://railmapgen.github.io/rmg/assets/chakra-0b0a1fde.js:16:132996     at https://railmapgen.github.io/rmg/assets/chakra-0b0a1fde.js:16:296899     at div     at https://railmapgen.github.io/rmg/assets/chakra-0b0a1fde.js:16:6186     at https://railmapgen.github.io/rmg/assets/chakra-0b0a1fde.js:16:132996     at https://railmapgen.github.io/rmg/assets/chakra-0b0a1fde.js:16:296899     at div     at https://railmapgen.github.io/rmg/assets/chakra-0b0a1fde.js:16:6186     at https://railmapgen.github.io/rmg/assets/chakra-0b0a1fde.js:16:132996     at https://railmapgen.github.io/rmg/assets/chakra-0b0a1fde.js:16:296899     at Fg (https://railmapgen.github.io/rmg/assets/index-b47975a7.js:1:118322)     at ma (https://railmapgen.github.io/rmg/assets/app-router-1fb209cd.js:11:113246)     at Sa (https://railmapgen.github.io/rmg/assets/app-router-1fb209cd.js:11:118199)     at Suspense     at t (https://railmapgen.github.io/rmg/assets/index-b47975a7.js:1:110250)     at Sv (https://railmapgen.github.io/rmg/assets/react-f83802c2.js:43:3231)     at zm (https://railmapgen.github.io/rmg/assets/react-f83802c2.js:43:6390)     at div     at https://railmapgen.github.io/rmg/assets/chakra-0b0a1fde.js:16:6186     at https://railmapgen.github.io/rmg/assets/chakra-0b0a1fde.js:16:132996     at https://railmapgen.github.io/rmg/assets/chakra-0b0a1fde.js:16:296899     at Nu (https://railmapgen.github.io/rmg/assets/index-b47975a7.js:1:117970)     at ah (https://railmapgen.github.io/rmg/assets/index-b47975a7.js:1:132454)     at yp (https://railmapgen.github.io/rmg/assets/chakra-0b0a1fde.js:16:134346)     at jh (https://railmapgen.github.io/rmg/assets/chakra-0b0a1fde.js:16:17560)     at zy (https://railmapgen.github.io/rmg/assets/chakra-0b0a1fde.js:16:6406)     at P_ (https://railmapgen.github.io/rmg/assets/chakra-0b0a1fde.js:16:133667)     at E_ (https://railmapgen.github.io/rmg/assets/chakra-0b0a1fde.js:16:134794)     at https://railmapgen.github.io/rmg/assets/chakra-0b0a1fde.js:16:246438     at nh (https://railmapgen.github.io/rmg/assets/index-b47975a7.js:1:132353)     at Nv (https://railmapgen.github.io/rmg/assets/react-f83802c2.js:43:5825)     at jm (https://railmapgen.github.io/rmg/assets/react-f83802c2.js:52:419)     at ch     at yi (https://railmapgen.github.io/rmg/assets/index-b47975a7.js:1:62519)     at dg (https://railmapgen.github.io/rmg/assets/index-b47975a7.js:25:2877)](https://railmapgen.github.io/rmg/#/?project=hRyuWPO3mRECDPMcAH0fH)

**Comment by kivenCRT** [comment]
这是网址，文件发不过来https://railmapgen.github.io/rmg/#/?project=hRyuWPO3mRECDPMcAH0fH

**Comment by wongchito** [comment]
Hi @kivenCRT ,

由於專案內容只儲存於閣下瀏覽器暫存檔內，因此我們無法透過閣下提供的網址訪問。閣下可嘗試下載JSON格式設定檔後，將其壓縮為ZIP格式再上載至此處。


@thekingofcity - Error stack trace顯示錯誤可能出現在 https://github.com/railmapgen/rmg/blob/main/src/svgs/shmetro/destination-shmetro.tsx#L144C1-L210C1 附近，但無法具體確定。

**Comment by kivenCRT** [comment]
好的，我已经下载了JSON文件准备压缩后发给您












Kiven
***@***.***



18375681978


---原始邮件---
发件人: "Chito ***@***.***&gt;
发送时间: 2023年7月31日(周一) 上午10:52
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [railmapgen/rmg] 关于上海地铁线路图切换其他风格后终点站线路牌显示错误 (Issue #565)




 
Hi @kivenCRT ,
 
由於專案內容只儲存於閣下瀏覽器暫存檔內，因此我們無法透過閣下提供的網址訪問。閣下可嘗試下載JSON格式設定檔後，將其壓縮為ZIP格式再上載至此處。
 
@thekingofcity - Error stack trace顯示錯誤可能出現在 https://github.com/railmapgen/rmg/blob/main/src/svgs/shmetro/destination-shmetro.tsx#L144C1-L210C1 附近，但無法具體確定。

**Comment by kivenCRT** [comment]
我已经发了文件，望请查收












Kiven
***@***.***



18375681978


---原始邮件---
发件人: "Chito ***@***.***&gt;
发送时间: 2023年7月31日(周一) 上午10:52
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [railmapgen/rmg] 关于上海地铁线路图切换其他风格后终点站线路牌显示错误 (Issue #565)




 
Hi @kivenCRT ,
 
由於專案內容只儲存於閣下瀏覽器暫存檔內，因此我們無法透過閣下提供的網址訪問。閣下可嘗試下載JSON格式設定檔後，將其壓縮為ZIP格式再上載至此處。
 
@thekingofcity - Error stack trace顯示錯誤可能出現在 https://github.com/railmapgen/rmg/blob/main/src/svgs/shmetro/destination-shmetro.tsx#L144C1-L210C1 附近，但無法具體確定。

**Comment by thekingofcity** [comment]
嗨，感谢汇报问题，方便将文件直接上传在议题的评论对话框中吗？chito 并没有收到您发送的文件，没有存档我们无法复现并验证修复问题，谢谢理解 :)

**Comment by thekingofcity** [comment]
Closed as no response :(
