### ISSUE TITLE
關於松山新店線切換至上海鐵路格式後，方向指示牌顯示不出來的事宜

### ISSUE THREAD

**Issue by Takagi-Misae** [railmapgen/rmg#569]
切換到上海鐵路後，不能顯示方向指示牌。
已經重新加載過，還是不行。瀏覽器已經是最新版本了，請修復，謝謝🙏

**Comment by Takagi-Misae** [comment]
是終點站牌

**Comment by Takagi-Misae** [comment]
https://github.com/railmapgen/rmg/assets/143057061/4e5176cb-708d-4418-9b24-e317ac0afaa3

[鐵路路綫圖產生器.pdf](https://github.com/railmapgen/rmg/files/12430142/default.pdf)

**Comment by thekingofcity** [comment]
嗨，我尝试导入松山新店線模板后，翻转整条路线，再设置松山为当前站，再将行车方向改为向右模拟截图所示情况，结果仍能正常显示 终点站 站牌。我需要一个完整的从导入模板开始的操作直至错误的流程才能展开调查。对于当前情况，您可以重新导入模板后尝试上述操作。如果仍然出错，请提供您的iPad OS版本，谢谢 :)

**Comment by Takagi-Misae** [comment]
現在可以了，謝謝🙏
