### ISSUE TITLE
關於路綫圖優化事宜

### ISSUE THREAD

**Issue by Charlis-Wong** [railmapgen/rmg#572]
致：RMG團隊
本人覺得在審核路綫圖上傳至範本時，應要更改到其他的風格然後測試，才決定批不批准上傳。因爲本人發現很多範本鐵路圖轉換成別的風格后，路綫的長度或者是版面的高度不匹配。

就例如：廣州地鐵四號綫
![螢幕擷取畫面 2023-08-30 125141](https://github.com/railmapgen/rmg/assets/143057061/5a4d2dbd-113e-4950-a037-0ca9df4f6c1e)
![螢幕擷取畫面 2023-08-30 125228](https://github.com/railmapgen/rmg/assets/143057061/9e3b1911-edf3-4f9d-ba70-cdbffffe0274)
用上海地鐵風格開出來之後，會發現終點站牌的長度不足，幕門路綫圖的高度不足

謝謝！

**Comment by wongchito** [comment]
Hi @Takagi-Misae ,

感謝閣下的查詢！

RMG設計初衷的確希望能夠使用同一份設定檔，於不同風格間切換，但後來發現，我們無法令其_完全_通用。例如，路線的垂直位置會因支線位置而不同（香港東鐵綫、廣州3號線、上海10號線）。

而RMG範本早期只接受三種風格對應的城市的路線，並需要按照現實的比例調整各參數，使其可重現真實的效果 。

因此，當我們放開RMG範本上載城市限制時，只會檢查內容及美觀程度，並不會詳細檢查於其他風格內的顯示效果。而我們亦相信，RMG已提供足夠簡單的方法，以微調參數，令其正確顯示。

多謝閣下的理解，亦歡迎閣下提出更優的建議！
