### ISSUE TITLE
關於人手不足問題

### ISSUE THREAD

**Issue by Takagi-Misae** [railmapgen/rmg#577]
你好，我想反映一下人手不足的問題。
有一些需要審核專案已經等待了一週或更久的時間
請問可不可以增加一些人手只要審核，程式的就留給管理員去做？

**Comment by wongchito** [comment]
Hi @Takagi-Misae ,

感謝閣下對於RMG的關注。

目前開發團隊以業餘愛好者為主，審核團隊大部份為學生，因此我們沒有足夠的時間應付大量的範本提交。

如閣下有意加入審核團隊，歡迎點擊「路綫圖工具組」左下角的Slack連結，加入我們的聊天群組。

**Comment by Takagi-Misae** [comment]
我十分有意思進入你們的審核團隊

**Comment by wongchito** [comment]
歡迎加入！
