### ISSUE TITLE
绘制支线时终点站方向字体间距出错

### ISSUE THREAD

**Issue by Misaka89535** [railmapgen/rmg#578]
在绘制支线时，如果两个终点站站名长度不一致，站名间距似乎就会存在间距问题。在手动键入空格后有所好转，不知道有无办法解决，谢谢！
![图片](https://github.com/railmapgen/rmg/assets/90268558/e20c3682-8cd5-443e-9413-2ee207352786)
![图片](https://github.com/railmapgen/rmg/assets/90268558/df39c9a1-7f0f-44a7-8716-ce53f4446b71)

**Comment by wongchito** [comment]
Hi @Misaka89535 ,

感謝閣下回報問題。經測試發現，該bug僅存在於Chrome (或Chromium) 瀏覽器中，而在Safari瀏覽器中能夠正確顯示。

我們現已為Chrome瀏覽器修復該問題。多謝閣下對RMG的關注！

<img width="296" alt="image" src="https://github.com/railmapgen/rmg/assets/9390786/95d4d292-5c6a-4ddd-be74-92bf069d2c5f">
<img width="260" alt="image" src="https://github.com/railmapgen/rmg/assets/9390786/7843f84e-a7a3-43af-b009-aff0900eae0e">
