### ISSUE TITLE
线路图工具包出问题了

### ISSUE THREAD

**Issue by xiliuxian-01** [railmapgen/rmg#604]
[RMG_vM4ASavTg1Vqr1BmRfXpv.json](https://github.com/railmapgen/rmg/files/13669962/RMG_vM4ASavTg1Vqr1BmRfXpv.json)
线路图工具包出问题了

**Comment by wongchito** [comment]
Hi @xiliuxian-01 ,

根據閣下提供的設定檔推測，閣下的最後動作為「於薊門橋站左側新增一個車站」，但我們無法復原該錯誤：即使循任何順序點選按鍵，均能正確地新增車站並插入正確的位置。

附修正後的檔案：[RMG_vM4ASavTg1Vqr1BmRfXpv_fixed.json](https://github.com/railmapgen/rmg/files/13704475/RMG_vM4ASavTg1Vqr1BmRfXpv.json)

如閣下再次遇到該問題，請將具體步驟提供予我們，以協助我們修正錯誤。多謝！
