### ISSUE TITLE
上海风格新出站换乘样式

### ISSUE THREAD

**Issue by 203IhzElttil** [railmapgen/rmg#620]
最近申通改的
![image](https://github.com/railmapgen/rmg/assets/106796352/97d26ddd-b66a-46eb-b0d1-c101975105ab)
![image](https://github.com/railmapgen/rmg/assets/106796352/e7defc49-0011-4eb1-85b9-5ec21c901ec5)
![image](https://github.com/railmapgen/rmg/assets/106796352/50cb3e46-f7e5-43bd-a3de-9d9c3faee6be)
（14曹杨路的那个出站换乘两个⚪好像偏下了，正确位置应该是娄山关路类

**Comment by thekingofcity** [comment]
![image](https://github.com/railmapgen/rmg/assets/3353040/cbded9cc-2c53-4826-af71-2bca1c616705)

https://www.xiaohongshu.com/discovery/item/65b03d36000000002b03f1e5

**Comment by thekingofcity** [comment]
![image](https://github.com/railmapgen/rmg/assets/3353040/09e67749-615f-4551-a355-2c381e965b4b)
