### ISSUE TITLE
出现了些问题

### ISSUE THREAD

**Issue by MingHu197** [railmapgen/rmg#634]
[rmg_BACKUP_2024-03-20T004030.879Z.json](https://github.com/railmapgen/rmg/files/14658940/rmg_BACKUP_2024-03-20T004030.879Z.json)

**Comment by wongchito** [comment]
Hi @MingHu197 ,

非常抱歉閣下遇到該情況。煩請閣下提供出現錯誤時的「詳細資訊」，多謝！
