### ISSUE TITLE
Advice: ADD PIDS PART 建议：添加车内显示屏模块PIDS

### ISSUE THREAD

**Issue by CatAlan1028** [railmapgen/rmg#636]
**！注意，这个建议可以作为远期实现加入到milestone中，毕竟你们现在人手不够**
**！注意，这个可以独立作为组件，并不一定要放在RMG中**
设想：（以深圳地铁为例）
实现效果包含：
PART1 下一站页面（显示小区间）
![image](https://github.com/railmapgen/rmg/assets/146333201/95ced117-bb3c-4882-8119-74be24597854)
需要素材：页面样式底图
需要信息：线路所有车站、线路编号、换乘情况、线路色号、前进方向
PART2 停靠站页面（显示当前车站信息）
![image](https://github.com/railmapgen/rmg/assets/146333201/c57025a4-d2ba-4952-b448-42891df9f63e)
需要素材：页面样式底图
需要信息：线路编号、线路色号、换乘情况、出口情况
可以添加的信息：电梯设施相对于车厢位置、车站为地上站还是地下站等
【可选】PART3 下一站页面（显示整个线路）但是这一个可能与RMG本身重复。
【可选】PART4 即将到站页面

**Comment by thekingofcity** [comment]
See #11
