### ISSUE TITLE
Fix MTR style terminal

### ISSUE THREAD

**Issue by jacksonvil-s** [railmapgen/rmg#643]
<img width="870" alt="image" src="https://github.com/railmapgen/railmapgen.github.io/assets/161327426/8a38a1c9-871c-4a6c-947e-3477579c14ee">
Currently the terminating looks like this.

It should look like this. (Look at the sign on the right)
![image](https://github.com/railmapgen/railmapgen.github.io/assets/161327426/ac1fbc65-3679-41ed-97e6-1f0291bbc07f)

Please fix this in RMG as it is a thing that is not realistic.

**Comment by CatAlan1028** [comment]
Yes, I have the same question.
Let's suggest a line has 2 terminals: A and B. **When the current station is set to A and the terminal is also set to A, this bug appears.** 
In this case, the _destination canvas_ should **only shows the current station name(i.e. the terminal name)** as is shown by @jacksonvil-s .And the _rail map canvas_ should **show nothing**.
是的，我也有相同的问题。
不妨假设一条线路有2个终点站：A和B。**当令A为当前车站且终点站也为A方向时，即会出现该问题。**
在这种情况下， _终点站门牌_ 应当就像@jacksonvil-s 所展示的那样**仅显示当前车站名（即该终点站名）**。同时， _站台门路线图_ 应当为**空白**。

**Comment by Swiftiecott** [comment]
> _终点站门牌_ 应当就像@jacksonvil-s 所展示的那样**仅显示当前车站名（即该终点站名）**。

实际上港铁的终点站屏蔽门盖板上并不会显示当前车站名。

由于港铁的屏蔽门盖板只会显示列车开往方向、站台编号以及线路图，因此在终点站的时候如果该站台列车并非站前折返的话屏蔽门盖板上除了站台编号外什么都不会标出，这一点在@jacksonvil-s 所提供的图片上已经有很明显体现。

**Comment by wongchito** [comment]
Hi @jacksonvil-s ,

Thanks for reporting. This has been fixed now.
