### ISSUE TITLE
how do i create an external line?

### ISSUE THREAD

**Issue by Enderman2452633YT** [railmapgen/rmg#645]

**Comment by thekingofcity** [comment]
Hi, to create an external line. Follow these steps:

1. Open the _Create a new line_ model from the bottom left add button next to the main line.
2. Choose _Create an external line_.
3. For _Between_ and _and_, choose the _LEFT END_ and the station where the line splits.
4. Add a new station in the new external line.
5. Both Railmap and Indoor canvas should work as expected.

Note: External line only works in the Shanghai Metro style and only works when one end of the external line is LEFT END or RIGHT END.

Feel free to comment and reopen if anything does not go as expected :)

<img width="1244" alt="image" src="https://github.com/user-attachments/assets/153fce86-0d13-4861-9d7f-baafb84de772">
