### ISSUE TITLE
咋回事 What’s the matter?

### ISSUE THREAD

**Issue by POPIEGGY32767** [railmapgen/rmg#650]
为什么会这样,我搞个支线,结果想删除,然后就显示错误页面了.代码:
TypeError: undefined is not an object (evaluating 'n.indexOf')

It@https://railmapgen.github.io/rmg/assets/index-D9gi3AWV.js:1:58849
svg
W@https://railmapgen.github.io/rmg/assets/share-DiicL0jS.js:1:176
bt@https://railmapgen.github.io/rmg/assets/index-D9gi3AWV.js:1:57283
t@https://railmapgen.github.io/rmg/assets/index-BjiIcav9.js:10:70787
div
@https://railmapgen.github.io/rmg/assets/chakra-DA8f5sL-.js:16:6190
@https://railmapgen.github.io/rmg/assets/chakra-DA8f5sL-.js:16:133918
@https://railmapgen.github.io/rmg/assets/chakra-DA8f5sL-.js:16:310483
Jr@https://railmapgen.github.io/rmg/assets/app-router-D49UwsPh.js:2:2731
div
@https://railmapgen.github.io/rmg/assets/chakra-DA8f5sL-.js:16:6190
@https://railmapgen.github.io/rmg/assets/chakra-DA8f5sL-.js:16:133918
section
@https://railmapgen.github.io/rmg/assets/chakra-DA8f5sL-.js:16:6190
@https://railmapgen.github.io/rmg/assets/chakra-DA8f5sL-.js:16:133918
@https://railmapgen.github.io/rmg/assets/chakra-DA8f5sL-.js:16:310483
div
@https://railmapgen.github.io/rmg/assets/chakra-DA8f5sL-.js:16:6190
@https://railmapgen.github.io/rmg/assets/chakra-DA8f5sL-.js:16:133918
@https://railmapgen.github.io/rmg/assets/chakra-DA8f5sL-.js:16:310483
div
@https://railmapgen.github.io/rmg/assets/chakra-DA8f5sL-.js:16:6190
@https://railmapgen.github.io/rmg/assets/chakra-DA8f5sL-.js:16:133918
@https://railmapgen.github.io/rmg/assets/chakra-DA8f5sL-.js:16:310483
Dv@https://railmapgen.github.io/rmg/assets/index-BjiIcav9.js:10:76738
mi@https://railmapgen.github.io/rmg/assets/app-router-D49UwsPh.js:12:110821
Ci@https://railmapgen.github.io/rmg/assets/app-router-D49UwsPh.js:12:116213
Suspense
t@https://railmapgen.github.io/rmg/assets/index-BjiIcav9.js:10:70787
qm@https://railmapgen.github.io/rmg/assets/react-B326QF9K.js:43:3377
Hy@https://railmapgen.github.io/rmg/assets/react-B326QF9K.js:43:7082
div
@https://railmapgen.github.io/rmg/assets/chakra-DA8f5sL-.js:16:6190
@https://railmapgen.github.io/rmg/assets/chakra-DA8f5sL-.js:16:133918
@https://railmapgen.github.io/rmg/assets/chakra-DA8f5sL-.js:16:310483
dm@https://railmapgen.github.io/rmg/assets/index-BjiIcav9.js:10:76291
Hm@https://railmapgen.github.io/rmg/assets/index-BjiIcav9.js:10:90752
EnvironmentProvider@https://railmapgen.github.io/rmg/assets/chakra-DA8f5sL-.js:16:135281
ColorModeProvider@https://railmapgen.github.io/rmg/assets/chakra-DA8f5sL-.js:16:17555
i0@https://railmapgen.github.io/rmg/assets/chakra-DA8f5sL-.js:16:6410
Y_@https://railmapgen.github.io/rmg/assets/chakra-DA8f5sL-.js:16:134596
Q_@https://railmapgen.github.io/rmg/assets/chakra-DA8f5sL-.js:16:135864
@https://railmapgen.github.io/rmg/assets/chakra-DA8f5sL-.js:16:257433
Fm@https://railmapgen.github.io/rmg/assets/index-BjiIcav9.js:10:90657
ov@https://railmapgen.github.io/rmg/assets/react-B326QF9K.js:43:6494
Qy@https://railmapgen.github.io/rmg/assets/react-B326QF9K.js:52:510
Jm
Wy@https://railmapgen.github.io/rmg/assets/react-B326QF9K.js:25:134369
Iy@https://railmapgen.github.io/rmg/assets/react-B326QF9K.js:60:2869
Main line
Press ENTER to sort

**Comment by thekingofcity** [comment]
嗨，很抱歉带来这样的问题，方便在左侧侧边栏-设置-导出本地存储中，复制并在此处粘贴 rmg-param d的内容吗？

**Comment by POPIEGGY32767** [comment]
ok


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年9月15日 10:00 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***>,
***@***.***> |
| 主题 | Re: [railmapgen/rmg] 咋回事 What’s the matter? (Issue #650) |

嗨，很抱歉带来这样的问题，方便在左侧侧边栏-设置-导出本地存储中，复制并在此处粘贴 rmg-param d的内容吗？

**Comment by thekingofcity** [comment]
Closed due to no response :(
