### ISSUE TITLE
Warning Overhead Wires

### ISSUE THREAD

**Issue by jacksonvil-s** [railmapgen/rmg#651]
I know this is just a little thing, but can you guys add a little "Warning Overhead Wires" as a page? (In MTR styled RMG)

![image](https://github.com/user-attachments/assets/d8ac5f09-a5bd-4465-b58c-096af9244b2a)

On the left, the little yellow thingy (this was the best one I can find)

**Comment by wongchito** [comment]
Hi @jacksonvil-s ,

Thanks for raising the request. Our team currently doesn't have the ability to draw such complicated signage, and we have concern (mainly copyright) using exiting signage on the internet. Hence we don't have a plan for adding these signages to RMG. 

However, it's always welcome if you could provide these kinds of signages with proper authorisation to us.
