### ISSUE TITLE
关于项目的求助问题

### ISSUE THREAD

**Issue by 13397081271** [railmapgen/rmg#655]
开发者们，你们好，我有个问题，这个超出数量了有啥解决办法吗，我想多一些设计线路。PS：我是第一次使用这个软件，有些功能我不太会，请谅解

![Snipaste_2024-09-18_21-04-38](https://github.com/user-attachments/assets/828f44af-3f8b-495c-bc15-ff5a39520523)

**Comment by wongchito** [comment]
Hi @13397081271 ,

由於瀏覽器限制了每個網站可使用的本地儲存空間，我們不得不設定網頁上的項目數量上限。閣下可使用「下載設定檔」功能，將項目儲存於本地檔案系統。

我們亦暫無意提高該上限。

多謝閣下的查詢。
