### ISSUE TITLE
Platform number cannot be shown in correct location

### ISSUE THREAD

**Issue by Bial109** [railmapgen/rmg#657]
As the screenshot shown above, when I use MTR style and the destination map with width 1200 and height 300, the platform number is located at the left of the map, which is not the location where the platform number should be at.
![rmg unJQps 未命名 unJQps Unnamed unJQps](https://github.com/user-attachments/assets/b9f84c45-0c15-41ab-88ce-1fa21ad1bfd4)

**Comment by wongchito** [comment]
Hi @Bial109 ,

Thanks for reporting. We’ve confirmed the issue and we’ll arrange a fix on it.
