### ISSUE TITLE
在rmg的广州地铁样式里的问题

### ISSUE THREAD

**Issue by CetiTrek** [railmapgen/rmg#660]
在rmg的广州地铁样式里，即使不输入中英文第二名称，也会有个括号，用rmp导出的rmg项目也有这个问题
如图
![1](https://github.com/user-attachments/assets/a9821495-adbc-409d-9176-67dceb9db08d)
![2](https://github.com/user-attachments/assets/5c3853c9-73ae-4c80-b7e2-7915506d9aff)

**Comment by wongchito** [comment]
Hi @CetiTrek ,

感謝閣下回報問題。我們現已提供開關以供閣下取消顯示單個車站的第二名稱。

<img width="872" alt="image" src="https://github.com/user-attachments/assets/95ffb710-9703-4aa0-bb3d-583866180f34">

關於RMP2RMG的轉換問題，將於railmapgen/rmp#865 中跟進。
