### ISSUE TITLE
能否导出矢量PDF

### ISSUE THREAD

**Issue by Firecj0987** [railmapgen/rmg#76]
目前这个项目只支持导出svg文件和png文件，svg图片对手机用户不太友好，而png
文件则不能很好地还原一些细节，希望可以导出矢量PDF，让手机用户查看更方便

**Comment by thekingofcity** [comment]
There are libraries like `jspdf` and `svg2pdf` that do some great work. However, debugging the pdf blocks me to investigate further. Following the doc will output a blank pdf file and it is hard to know what's going on inside and what is missing in the pdf. Moreover, the utf-8 fonts need to be manually loaded and in `ttf` formats.

**Comment by thekingofcity** [comment]
```
const doc = new jsPDF();
const data = elem.outerHTML;
// either this
doc.addSvgAsImage(data, 0, 0, 1500, Number(elem.getAttribute('height')));
// or this
await doc.svg(elem,
    {
        x:0,
        y:0,
        width:thisSVGWidth,
        height:thisSVGHeight
    });
// will work
saveAs(URL.createObjectURL(doc.output('blob')), `${filename}.pdf`);
```

**Comment by wongchito** [comment]
Close as requirement is not feasible. Reopen is welcome if there’s a better solution.
